/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser.
 * Use it to get access to models, enums, and input types.
 *
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from "./internal/prismaNamespaceBrowser.ts";
export { Prisma };
export * as $Enums from "./enums.ts";
export * from "./enums.ts";
/**
 * Model User
 *
 */
export type User = Prisma.UserModel;
/**
 * Model Faith
 *
 */
export type Faith = Prisma.FaithModel;
/**
 * Model Tithe
 *
 */
export type Tithe = Prisma.TitheModel;
/**
 * Model Offer
 *
 */
export type Offer = Prisma.OfferModel;
/**
 * Model Cash
 *
 */
export type Cash = Prisma.CashModel;
/**
 * Model CashHub
 *
 */
export type CashHub = Prisma.CashHubModel;
/**
 * Model Bank
 *
 */
export type Bank = Prisma.BankModel;
/**
 * Model BankHub
 *
 */
export type BankHub = Prisma.BankHubModel;
/**
 * Model Pix
 *
 */
export type Pix = Prisma.PixModel;
/**
 * Model Payment
 *
 */
export type Payment = Prisma.PaymentModel;
/**
 * Model Invoice
 *
 */
export type Invoice = Prisma.InvoiceModel;
/**
 * Model InvoiceLog
 *
 */
export type InvoiceLog = Prisma.InvoiceLogModel;
