/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client";
import * as $Enums from "./enums.ts";
import type * as Prisma from "./internal/prismaNamespace.ts";

export type StringFilter<$PrismaModel = never> = {
    equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
    notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
    lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    mode?: Prisma.QueryMode;
    not?: Prisma.NestedStringFilter<$PrismaModel> | string;
};

export type DateTimeFilter<$PrismaModel = never> = {
    equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
    notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
    lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string;
};

export type EnumGenderEnumFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.GenderEnum
        | Prisma.EnumGenderEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.GenderEnum[]
        | Prisma.ListEnumGenderEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.GenderEnum[]
        | Prisma.ListEnumGenderEnumFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedEnumGenderEnumFilter<$PrismaModel> | $Enums.GenderEnum;
};

export type DecimalNullableFilter<$PrismaModel = never> = {
    equals?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>
        | null;
    in?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>
        | null;
    notIn?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>
        | null;
    lt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    lte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedDecimalNullableFilter<$PrismaModel>
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | null;
};

export type BoolFilter<$PrismaModel = never> = {
    equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean;
};

export type SortOrderInput = {
    sort: Prisma.SortOrder;
    nulls?: Prisma.NullsOrder;
};

export type StringWithAggregatesFilter<$PrismaModel = never> = {
    equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
    notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
    lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    mode?: Prisma.QueryMode;
    not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedStringFilter<$PrismaModel>;
    _max?: Prisma.NestedStringFilter<$PrismaModel>;
};

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
    equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
    notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
    lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel>
        | Date
        | string;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedDateTimeFilter<$PrismaModel>;
    _max?: Prisma.NestedDateTimeFilter<$PrismaModel>;
};

export type EnumGenderEnumWithAggregatesFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.GenderEnum
        | Prisma.EnumGenderEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.GenderEnum[]
        | Prisma.ListEnumGenderEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.GenderEnum[]
        | Prisma.ListEnumGenderEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumGenderEnumWithAggregatesFilter<$PrismaModel>
        | $Enums.GenderEnum;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumGenderEnumFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumGenderEnumFilter<$PrismaModel>;
};

export type DecimalNullableWithAggregatesFilter<$PrismaModel = never> = {
    equals?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>
        | null;
    in?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>
        | null;
    notIn?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>
        | null;
    lt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    lte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedDecimalNullableWithAggregatesFilter<$PrismaModel>
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | null;
    _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
    _avg?: Prisma.NestedDecimalNullableFilter<$PrismaModel>;
    _sum?: Prisma.NestedDecimalNullableFilter<$PrismaModel>;
    _min?: Prisma.NestedDecimalNullableFilter<$PrismaModel>;
    _max?: Prisma.NestedDecimalNullableFilter<$PrismaModel>;
};

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
    equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedBoolFilter<$PrismaModel>;
    _max?: Prisma.NestedBoolFilter<$PrismaModel>;
};

export type IntFilter<$PrismaModel = never> = {
    equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
    notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
    lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedIntFilter<$PrismaModel> | number;
};

export type IntWithAggregatesFilter<$PrismaModel = never> = {
    equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
    notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
    lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
    _sum?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedIntFilter<$PrismaModel>;
    _max?: Prisma.NestedIntFilter<$PrismaModel>;
};

export type DecimalFilter<$PrismaModel = never> = {
    equals?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    in?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>;
    notIn?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>;
    lt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    lte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedDecimalFilter<$PrismaModel>
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
};

export type DecimalWithAggregatesFilter<$PrismaModel = never> = {
    equals?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    in?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>;
    notIn?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>;
    lt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    lte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedDecimalWithAggregatesFilter<$PrismaModel>
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _avg?: Prisma.NestedDecimalFilter<$PrismaModel>;
    _sum?: Prisma.NestedDecimalFilter<$PrismaModel>;
    _min?: Prisma.NestedDecimalFilter<$PrismaModel>;
    _max?: Prisma.NestedDecimalFilter<$PrismaModel>;
};

export type EnumBankEnumFilter<$PrismaModel = never> = {
    equals?: $Enums.BankEnum | Prisma.EnumBankEnumFieldRefInput<$PrismaModel>;
    in?: $Enums.BankEnum[] | Prisma.ListEnumBankEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.BankEnum[]
        | Prisma.ListEnumBankEnumFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedEnumBankEnumFilter<$PrismaModel> | $Enums.BankEnum;
};

export type EnumBankEnumWithAggregatesFilter<$PrismaModel = never> = {
    equals?: $Enums.BankEnum | Prisma.EnumBankEnumFieldRefInput<$PrismaModel>;
    in?: $Enums.BankEnum[] | Prisma.ListEnumBankEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.BankEnum[]
        | Prisma.ListEnumBankEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumBankEnumWithAggregatesFilter<$PrismaModel>
        | $Enums.BankEnum;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumBankEnumFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumBankEnumFilter<$PrismaModel>;
};

export type StringNullableFilter<$PrismaModel = never> = {
    equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
    in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
    notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
    lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    mode?: Prisma.QueryMode;
    not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null;
};

export type EnumPixEnumFilter<$PrismaModel = never> = {
    equals?: $Enums.PixEnum | Prisma.EnumPixEnumFieldRefInput<$PrismaModel>;
    in?: $Enums.PixEnum[] | Prisma.ListEnumPixEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.PixEnum[]
        | Prisma.ListEnumPixEnumFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedEnumPixEnumFilter<$PrismaModel> | $Enums.PixEnum;
};

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
    equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
    in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
    notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
    lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    mode?: Prisma.QueryMode;
    not?:
        | Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel>
        | string
        | null;
    _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
    _min?: Prisma.NestedStringNullableFilter<$PrismaModel>;
    _max?: Prisma.NestedStringNullableFilter<$PrismaModel>;
};

export type EnumPixEnumWithAggregatesFilter<$PrismaModel = never> = {
    equals?: $Enums.PixEnum | Prisma.EnumPixEnumFieldRefInput<$PrismaModel>;
    in?: $Enums.PixEnum[] | Prisma.ListEnumPixEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.PixEnum[]
        | Prisma.ListEnumPixEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumPixEnumWithAggregatesFilter<$PrismaModel>
        | $Enums.PixEnum;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumPixEnumFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumPixEnumFilter<$PrismaModel>;
};

export type EnumInvoiceEnumFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.InvoiceEnum
        | Prisma.EnumInvoiceEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.InvoiceEnum[]
        | Prisma.ListEnumInvoiceEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.InvoiceEnum[]
        | Prisma.ListEnumInvoiceEnumFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedEnumInvoiceEnumFilter<$PrismaModel> | $Enums.InvoiceEnum;
};

export type EnumTransferEnumFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.TransferEnum
        | Prisma.EnumTransferEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.TransferEnum[]
        | Prisma.ListEnumTransferEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.TransferEnum[]
        | Prisma.ListEnumTransferEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumTransferEnumFilter<$PrismaModel>
        | $Enums.TransferEnum;
};

export type EnumInvoiceEnumWithAggregatesFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.InvoiceEnum
        | Prisma.EnumInvoiceEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.InvoiceEnum[]
        | Prisma.ListEnumInvoiceEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.InvoiceEnum[]
        | Prisma.ListEnumInvoiceEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumInvoiceEnumWithAggregatesFilter<$PrismaModel>
        | $Enums.InvoiceEnum;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumInvoiceEnumFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumInvoiceEnumFilter<$PrismaModel>;
};

export type EnumTransferEnumWithAggregatesFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.TransferEnum
        | Prisma.EnumTransferEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.TransferEnum[]
        | Prisma.ListEnumTransferEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.TransferEnum[]
        | Prisma.ListEnumTransferEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumTransferEnumWithAggregatesFilter<$PrismaModel>
        | $Enums.TransferEnum;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumTransferEnumFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumTransferEnumFilter<$PrismaModel>;
};

export type NestedStringFilter<$PrismaModel = never> = {
    equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
    notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
    lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedStringFilter<$PrismaModel> | string;
};

export type NestedDateTimeFilter<$PrismaModel = never> = {
    equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
    notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
    lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string;
};

export type NestedEnumGenderEnumFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.GenderEnum
        | Prisma.EnumGenderEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.GenderEnum[]
        | Prisma.ListEnumGenderEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.GenderEnum[]
        | Prisma.ListEnumGenderEnumFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedEnumGenderEnumFilter<$PrismaModel> | $Enums.GenderEnum;
};

export type NestedDecimalNullableFilter<$PrismaModel = never> = {
    equals?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>
        | null;
    in?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>
        | null;
    notIn?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>
        | null;
    lt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    lte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedDecimalNullableFilter<$PrismaModel>
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | null;
};

export type NestedBoolFilter<$PrismaModel = never> = {
    equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean;
};

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
    equals?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
    notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
    lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedStringFilter<$PrismaModel>;
    _max?: Prisma.NestedStringFilter<$PrismaModel>;
};

export type NestedIntFilter<$PrismaModel = never> = {
    equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
    notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
    lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedIntFilter<$PrismaModel> | number;
};

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
    equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
    notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>;
    lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel>
        | Date
        | string;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedDateTimeFilter<$PrismaModel>;
    _max?: Prisma.NestedDateTimeFilter<$PrismaModel>;
};

export type NestedEnumGenderEnumWithAggregatesFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.GenderEnum
        | Prisma.EnumGenderEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.GenderEnum[]
        | Prisma.ListEnumGenderEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.GenderEnum[]
        | Prisma.ListEnumGenderEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumGenderEnumWithAggregatesFilter<$PrismaModel>
        | $Enums.GenderEnum;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumGenderEnumFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumGenderEnumFilter<$PrismaModel>;
};

export type NestedDecimalNullableWithAggregatesFilter<$PrismaModel = never> = {
    equals?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>
        | null;
    in?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>
        | null;
    notIn?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>
        | null;
    lt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    lte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedDecimalNullableWithAggregatesFilter<$PrismaModel>
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | null;
    _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
    _avg?: Prisma.NestedDecimalNullableFilter<$PrismaModel>;
    _sum?: Prisma.NestedDecimalNullableFilter<$PrismaModel>;
    _min?: Prisma.NestedDecimalNullableFilter<$PrismaModel>;
    _max?: Prisma.NestedDecimalNullableFilter<$PrismaModel>;
};

export type NestedIntNullableFilter<$PrismaModel = never> = {
    equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null;
    in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
    notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null;
    lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null;
};

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
    equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedBoolFilter<$PrismaModel>;
    _max?: Prisma.NestedBoolFilter<$PrismaModel>;
};

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
    equals?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
    notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>;
    lt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    lte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    gt?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    gte?: number | Prisma.IntFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _avg?: Prisma.NestedFloatFilter<$PrismaModel>;
    _sum?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedIntFilter<$PrismaModel>;
    _max?: Prisma.NestedIntFilter<$PrismaModel>;
};

export type NestedFloatFilter<$PrismaModel = never> = {
    equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
    in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
    notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>;
    lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
    lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
    gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
    gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedFloatFilter<$PrismaModel> | number;
};

export type NestedDecimalFilter<$PrismaModel = never> = {
    equals?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    in?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>;
    notIn?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>;
    lt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    lte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedDecimalFilter<$PrismaModel>
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
};

export type NestedDecimalWithAggregatesFilter<$PrismaModel = never> = {
    equals?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    in?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>;
    notIn?:
        | runtime.Decimal[]
        | runtime.DecimalJsLike[]
        | number[]
        | string[]
        | Prisma.ListDecimalFieldRefInput<$PrismaModel>;
    lt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    lte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gt?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    gte?:
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string
        | Prisma.DecimalFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedDecimalWithAggregatesFilter<$PrismaModel>
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _avg?: Prisma.NestedDecimalFilter<$PrismaModel>;
    _sum?: Prisma.NestedDecimalFilter<$PrismaModel>;
    _min?: Prisma.NestedDecimalFilter<$PrismaModel>;
    _max?: Prisma.NestedDecimalFilter<$PrismaModel>;
};

export type NestedEnumBankEnumFilter<$PrismaModel = never> = {
    equals?: $Enums.BankEnum | Prisma.EnumBankEnumFieldRefInput<$PrismaModel>;
    in?: $Enums.BankEnum[] | Prisma.ListEnumBankEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.BankEnum[]
        | Prisma.ListEnumBankEnumFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedEnumBankEnumFilter<$PrismaModel> | $Enums.BankEnum;
};

export type NestedEnumBankEnumWithAggregatesFilter<$PrismaModel = never> = {
    equals?: $Enums.BankEnum | Prisma.EnumBankEnumFieldRefInput<$PrismaModel>;
    in?: $Enums.BankEnum[] | Prisma.ListEnumBankEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.BankEnum[]
        | Prisma.ListEnumBankEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumBankEnumWithAggregatesFilter<$PrismaModel>
        | $Enums.BankEnum;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumBankEnumFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumBankEnumFilter<$PrismaModel>;
};

export type NestedStringNullableFilter<$PrismaModel = never> = {
    equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
    in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
    notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
    lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null;
};

export type NestedEnumPixEnumFilter<$PrismaModel = never> = {
    equals?: $Enums.PixEnum | Prisma.EnumPixEnumFieldRefInput<$PrismaModel>;
    in?: $Enums.PixEnum[] | Prisma.ListEnumPixEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.PixEnum[]
        | Prisma.ListEnumPixEnumFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedEnumPixEnumFilter<$PrismaModel> | $Enums.PixEnum;
};

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
    equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
    in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
    notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
    lt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    lte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gt?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    gte?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    contains?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel>
        | string
        | null;
    _count?: Prisma.NestedIntNullableFilter<$PrismaModel>;
    _min?: Prisma.NestedStringNullableFilter<$PrismaModel>;
    _max?: Prisma.NestedStringNullableFilter<$PrismaModel>;
};

export type NestedEnumPixEnumWithAggregatesFilter<$PrismaModel = never> = {
    equals?: $Enums.PixEnum | Prisma.EnumPixEnumFieldRefInput<$PrismaModel>;
    in?: $Enums.PixEnum[] | Prisma.ListEnumPixEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.PixEnum[]
        | Prisma.ListEnumPixEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumPixEnumWithAggregatesFilter<$PrismaModel>
        | $Enums.PixEnum;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumPixEnumFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumPixEnumFilter<$PrismaModel>;
};

export type NestedEnumInvoiceEnumFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.InvoiceEnum
        | Prisma.EnumInvoiceEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.InvoiceEnum[]
        | Prisma.ListEnumInvoiceEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.InvoiceEnum[]
        | Prisma.ListEnumInvoiceEnumFieldRefInput<$PrismaModel>;
    not?: Prisma.NestedEnumInvoiceEnumFilter<$PrismaModel> | $Enums.InvoiceEnum;
};

export type NestedEnumTransferEnumFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.TransferEnum
        | Prisma.EnumTransferEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.TransferEnum[]
        | Prisma.ListEnumTransferEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.TransferEnum[]
        | Prisma.ListEnumTransferEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumTransferEnumFilter<$PrismaModel>
        | $Enums.TransferEnum;
};

export type NestedEnumInvoiceEnumWithAggregatesFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.InvoiceEnum
        | Prisma.EnumInvoiceEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.InvoiceEnum[]
        | Prisma.ListEnumInvoiceEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.InvoiceEnum[]
        | Prisma.ListEnumInvoiceEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumInvoiceEnumWithAggregatesFilter<$PrismaModel>
        | $Enums.InvoiceEnum;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumInvoiceEnumFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumInvoiceEnumFilter<$PrismaModel>;
};

export type NestedEnumTransferEnumWithAggregatesFilter<$PrismaModel = never> = {
    equals?:
        | $Enums.TransferEnum
        | Prisma.EnumTransferEnumFieldRefInput<$PrismaModel>;
    in?:
        | $Enums.TransferEnum[]
        | Prisma.ListEnumTransferEnumFieldRefInput<$PrismaModel>;
    notIn?:
        | $Enums.TransferEnum[]
        | Prisma.ListEnumTransferEnumFieldRefInput<$PrismaModel>;
    not?:
        | Prisma.NestedEnumTransferEnumWithAggregatesFilter<$PrismaModel>
        | $Enums.TransferEnum;
    _count?: Prisma.NestedIntFilter<$PrismaModel>;
    _min?: Prisma.NestedEnumTransferEnumFilter<$PrismaModel>;
    _max?: Prisma.NestedEnumTransferEnumFilter<$PrismaModel>;
};
