/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Cash` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model Cash
 *
 */
export type CashModel =
    runtime.Types.Result.DefaultSelection<Prisma.$CashPayload>;

export type AggregateCash = {
    _count: CashCountAggregateOutputType | null;
    _avg: CashAvgAggregateOutputType | null;
    _sum: CashSumAggregateOutputType | null;
    _min: CashMinAggregateOutputType | null;
    _max: CashMaxAggregateOutputType | null;
};

export type CashAvgAggregateOutputType = {
    balance: runtime.Decimal | null;
};

export type CashSumAggregateOutputType = {
    balance: runtime.Decimal | null;
};

export type CashMinAggregateOutputType = {
    id: string | null;
    balance: runtime.Decimal | null;
    userId: string | null;
    createdAt: Date | null;
    updatedAt: Date | null;
};

export type CashMaxAggregateOutputType = {
    id: string | null;
    balance: runtime.Decimal | null;
    userId: string | null;
    createdAt: Date | null;
    updatedAt: Date | null;
};

export type CashCountAggregateOutputType = {
    id: number;
    balance: number;
    userId: number;
    createdAt: number;
    updatedAt: number;
    _all: number;
};

export type CashAvgAggregateInputType = {
    balance?: true;
};

export type CashSumAggregateInputType = {
    balance?: true;
};

export type CashMinAggregateInputType = {
    id?: true;
    balance?: true;
    userId?: true;
    createdAt?: true;
    updatedAt?: true;
};

export type CashMaxAggregateInputType = {
    id?: true;
    balance?: true;
    userId?: true;
    createdAt?: true;
    updatedAt?: true;
};

export type CashCountAggregateInputType = {
    id?: true;
    balance?: true;
    userId?: true;
    createdAt?: true;
    updatedAt?: true;
    _all?: true;
};

export type CashAggregateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which Cash to aggregate.
     */
    where?: Prisma.CashWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Cash to fetch.
     */
    orderBy?:
        | Prisma.CashOrderByWithRelationInput
        | Prisma.CashOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.CashWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Cash from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Cash.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned Cash
     **/
    _count?: true | CashCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to average
     **/
    _avg?: CashAvgAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to sum
     **/
    _sum?: CashSumAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: CashMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: CashMaxAggregateInputType;
};

export type GetCashAggregateType<T extends CashAggregateArgs> = {
    [P in keyof T & keyof AggregateCash]: P extends "_count" | "count"
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateCash[P]>
        : Prisma.GetScalarType<T[P], AggregateCash[P]>;
};

export type CashGroupByArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.CashWhereInput;
    orderBy?:
        | Prisma.CashOrderByWithAggregationInput
        | Prisma.CashOrderByWithAggregationInput[];
    by: Prisma.CashScalarFieldEnum[] | Prisma.CashScalarFieldEnum;
    having?: Prisma.CashScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: CashCountAggregateInputType | true;
    _avg?: CashAvgAggregateInputType;
    _sum?: CashSumAggregateInputType;
    _min?: CashMinAggregateInputType;
    _max?: CashMaxAggregateInputType;
};

export type CashGroupByOutputType = {
    id: string;
    balance: runtime.Decimal;
    userId: string;
    createdAt: Date;
    updatedAt: Date;
    _count: CashCountAggregateOutputType | null;
    _avg: CashAvgAggregateOutputType | null;
    _sum: CashSumAggregateOutputType | null;
    _min: CashMinAggregateOutputType | null;
    _max: CashMaxAggregateOutputType | null;
};

export type GetCashGroupByPayload<T extends CashGroupByArgs> =
    Prisma.PrismaPromise<
        Array<
            Prisma.PickEnumerable<CashGroupByOutputType, T["by"]> & {
                [P in keyof T & keyof CashGroupByOutputType]: P extends "_count"
                    ? T[P] extends boolean
                        ? number
                        : Prisma.GetScalarType<T[P], CashGroupByOutputType[P]>
                    : Prisma.GetScalarType<T[P], CashGroupByOutputType[P]>;
            }
        >
    >;

export type CashWhereInput = {
    AND?: Prisma.CashWhereInput | Prisma.CashWhereInput[];
    OR?: Prisma.CashWhereInput[];
    NOT?: Prisma.CashWhereInput | Prisma.CashWhereInput[];
    id?: Prisma.StringFilter<"Cash"> | string;
    balance?:
        | Prisma.DecimalFilter<"Cash">
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    userId?: Prisma.StringFilter<"Cash"> | string;
    createdAt?: Prisma.DateTimeFilter<"Cash"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"Cash"> | Date | string;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
    cashesHub?: Prisma.CashHubListRelationFilter;
};

export type CashOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    balance?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    user?: Prisma.UserOrderByWithRelationInput;
    cashesHub?: Prisma.CashHubOrderByRelationAggregateInput;
};

export type CashWhereUniqueInput = Prisma.AtLeast<
    {
        id?: string;
        AND?: Prisma.CashWhereInput | Prisma.CashWhereInput[];
        OR?: Prisma.CashWhereInput[];
        NOT?: Prisma.CashWhereInput | Prisma.CashWhereInput[];
        balance?:
            | Prisma.DecimalFilter<"Cash">
            | runtime.Decimal
            | runtime.DecimalJsLike
            | number
            | string;
        userId?: Prisma.StringFilter<"Cash"> | string;
        createdAt?: Prisma.DateTimeFilter<"Cash"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"Cash"> | Date | string;
        user?: Prisma.XOR<
            Prisma.UserScalarRelationFilter,
            Prisma.UserWhereInput
        >;
        cashesHub?: Prisma.CashHubListRelationFilter;
    },
    "id"
>;

export type CashOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    balance?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    _count?: Prisma.CashCountOrderByAggregateInput;
    _avg?: Prisma.CashAvgOrderByAggregateInput;
    _max?: Prisma.CashMaxOrderByAggregateInput;
    _min?: Prisma.CashMinOrderByAggregateInput;
    _sum?: Prisma.CashSumOrderByAggregateInput;
};

export type CashScalarWhereWithAggregatesInput = {
    AND?:
        | Prisma.CashScalarWhereWithAggregatesInput
        | Prisma.CashScalarWhereWithAggregatesInput[];
    OR?: Prisma.CashScalarWhereWithAggregatesInput[];
    NOT?:
        | Prisma.CashScalarWhereWithAggregatesInput
        | Prisma.CashScalarWhereWithAggregatesInput[];
    id?: Prisma.StringWithAggregatesFilter<"Cash"> | string;
    balance?:
        | Prisma.DecimalWithAggregatesFilter<"Cash">
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    userId?: Prisma.StringWithAggregatesFilter<"Cash"> | string;
    createdAt?: Prisma.DateTimeWithAggregatesFilter<"Cash"> | Date | string;
    updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Cash"> | Date | string;
};

export type CashCreateInput = {
    id?: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    user: Prisma.UserCreateNestedOneWithoutCashesInput;
    cashesHub?: Prisma.CashHubCreateNestedManyWithoutCashInput;
};

export type CashUncheckedCreateInput = {
    id?: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    userId: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    cashesHub?: Prisma.CashHubUncheckedCreateNestedManyWithoutCashInput;
};

export type CashUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    user?: Prisma.UserUpdateOneRequiredWithoutCashesNestedInput;
    cashesHub?: Prisma.CashHubUpdateManyWithoutCashNestedInput;
};

export type CashUncheckedUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    cashesHub?: Prisma.CashHubUncheckedUpdateManyWithoutCashNestedInput;
};

export type CashCreateManyInput = {
    id?: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    userId: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type CashUpdateManyMutationInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CashUncheckedUpdateManyInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CashListRelationFilter = {
    every?: Prisma.CashWhereInput;
    some?: Prisma.CashWhereInput;
    none?: Prisma.CashWhereInput;
};

export type CashOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder;
};

export type CashCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    balance?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type CashAvgOrderByAggregateInput = {
    balance?: Prisma.SortOrder;
};

export type CashMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    balance?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type CashMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    balance?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type CashSumOrderByAggregateInput = {
    balance?: Prisma.SortOrder;
};

export type CashScalarRelationFilter = {
    is?: Prisma.CashWhereInput;
    isNot?: Prisma.CashWhereInput;
};

export type CashCreateNestedManyWithoutUserInput = {
    create?:
        | Prisma.XOR<
              Prisma.CashCreateWithoutUserInput,
              Prisma.CashUncheckedCreateWithoutUserInput
          >
        | Prisma.CashCreateWithoutUserInput[]
        | Prisma.CashUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.CashCreateOrConnectWithoutUserInput
        | Prisma.CashCreateOrConnectWithoutUserInput[];
    createMany?: Prisma.CashCreateManyUserInputEnvelope;
    connect?: Prisma.CashWhereUniqueInput | Prisma.CashWhereUniqueInput[];
};

export type CashUncheckedCreateNestedManyWithoutUserInput = {
    create?:
        | Prisma.XOR<
              Prisma.CashCreateWithoutUserInput,
              Prisma.CashUncheckedCreateWithoutUserInput
          >
        | Prisma.CashCreateWithoutUserInput[]
        | Prisma.CashUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.CashCreateOrConnectWithoutUserInput
        | Prisma.CashCreateOrConnectWithoutUserInput[];
    createMany?: Prisma.CashCreateManyUserInputEnvelope;
    connect?: Prisma.CashWhereUniqueInput | Prisma.CashWhereUniqueInput[];
};

export type CashUpdateManyWithoutUserNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.CashCreateWithoutUserInput,
              Prisma.CashUncheckedCreateWithoutUserInput
          >
        | Prisma.CashCreateWithoutUserInput[]
        | Prisma.CashUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.CashCreateOrConnectWithoutUserInput
        | Prisma.CashCreateOrConnectWithoutUserInput[];
    upsert?:
        | Prisma.CashUpsertWithWhereUniqueWithoutUserInput
        | Prisma.CashUpsertWithWhereUniqueWithoutUserInput[];
    createMany?: Prisma.CashCreateManyUserInputEnvelope;
    set?: Prisma.CashWhereUniqueInput | Prisma.CashWhereUniqueInput[];
    disconnect?: Prisma.CashWhereUniqueInput | Prisma.CashWhereUniqueInput[];
    delete?: Prisma.CashWhereUniqueInput | Prisma.CashWhereUniqueInput[];
    connect?: Prisma.CashWhereUniqueInput | Prisma.CashWhereUniqueInput[];
    update?:
        | Prisma.CashUpdateWithWhereUniqueWithoutUserInput
        | Prisma.CashUpdateWithWhereUniqueWithoutUserInput[];
    updateMany?:
        | Prisma.CashUpdateManyWithWhereWithoutUserInput
        | Prisma.CashUpdateManyWithWhereWithoutUserInput[];
    deleteMany?: Prisma.CashScalarWhereInput | Prisma.CashScalarWhereInput[];
};

export type CashUncheckedUpdateManyWithoutUserNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.CashCreateWithoutUserInput,
              Prisma.CashUncheckedCreateWithoutUserInput
          >
        | Prisma.CashCreateWithoutUserInput[]
        | Prisma.CashUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.CashCreateOrConnectWithoutUserInput
        | Prisma.CashCreateOrConnectWithoutUserInput[];
    upsert?:
        | Prisma.CashUpsertWithWhereUniqueWithoutUserInput
        | Prisma.CashUpsertWithWhereUniqueWithoutUserInput[];
    createMany?: Prisma.CashCreateManyUserInputEnvelope;
    set?: Prisma.CashWhereUniqueInput | Prisma.CashWhereUniqueInput[];
    disconnect?: Prisma.CashWhereUniqueInput | Prisma.CashWhereUniqueInput[];
    delete?: Prisma.CashWhereUniqueInput | Prisma.CashWhereUniqueInput[];
    connect?: Prisma.CashWhereUniqueInput | Prisma.CashWhereUniqueInput[];
    update?:
        | Prisma.CashUpdateWithWhereUniqueWithoutUserInput
        | Prisma.CashUpdateWithWhereUniqueWithoutUserInput[];
    updateMany?:
        | Prisma.CashUpdateManyWithWhereWithoutUserInput
        | Prisma.CashUpdateManyWithWhereWithoutUserInput[];
    deleteMany?: Prisma.CashScalarWhereInput | Prisma.CashScalarWhereInput[];
};

export type CashCreateNestedOneWithoutCashesHubInput = {
    create?: Prisma.XOR<
        Prisma.CashCreateWithoutCashesHubInput,
        Prisma.CashUncheckedCreateWithoutCashesHubInput
    >;
    connectOrCreate?: Prisma.CashCreateOrConnectWithoutCashesHubInput;
    connect?: Prisma.CashWhereUniqueInput;
};

export type CashUpdateOneRequiredWithoutCashesHubNestedInput = {
    create?: Prisma.XOR<
        Prisma.CashCreateWithoutCashesHubInput,
        Prisma.CashUncheckedCreateWithoutCashesHubInput
    >;
    connectOrCreate?: Prisma.CashCreateOrConnectWithoutCashesHubInput;
    upsert?: Prisma.CashUpsertWithoutCashesHubInput;
    connect?: Prisma.CashWhereUniqueInput;
    update?: Prisma.XOR<
        Prisma.XOR<
            Prisma.CashUpdateToOneWithWhereWithoutCashesHubInput,
            Prisma.CashUpdateWithoutCashesHubInput
        >,
        Prisma.CashUncheckedUpdateWithoutCashesHubInput
    >;
};

export type CashCreateWithoutUserInput = {
    id?: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    cashesHub?: Prisma.CashHubCreateNestedManyWithoutCashInput;
};

export type CashUncheckedCreateWithoutUserInput = {
    id?: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    cashesHub?: Prisma.CashHubUncheckedCreateNestedManyWithoutCashInput;
};

export type CashCreateOrConnectWithoutUserInput = {
    where: Prisma.CashWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.CashCreateWithoutUserInput,
        Prisma.CashUncheckedCreateWithoutUserInput
    >;
};

export type CashCreateManyUserInputEnvelope = {
    data: Prisma.CashCreateManyUserInput | Prisma.CashCreateManyUserInput[];
    skipDuplicates?: boolean;
};

export type CashUpsertWithWhereUniqueWithoutUserInput = {
    where: Prisma.CashWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.CashUpdateWithoutUserInput,
        Prisma.CashUncheckedUpdateWithoutUserInput
    >;
    create: Prisma.XOR<
        Prisma.CashCreateWithoutUserInput,
        Prisma.CashUncheckedCreateWithoutUserInput
    >;
};

export type CashUpdateWithWhereUniqueWithoutUserInput = {
    where: Prisma.CashWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.CashUpdateWithoutUserInput,
        Prisma.CashUncheckedUpdateWithoutUserInput
    >;
};

export type CashUpdateManyWithWhereWithoutUserInput = {
    where: Prisma.CashScalarWhereInput;
    data: Prisma.XOR<
        Prisma.CashUpdateManyMutationInput,
        Prisma.CashUncheckedUpdateManyWithoutUserInput
    >;
};

export type CashScalarWhereInput = {
    AND?: Prisma.CashScalarWhereInput | Prisma.CashScalarWhereInput[];
    OR?: Prisma.CashScalarWhereInput[];
    NOT?: Prisma.CashScalarWhereInput | Prisma.CashScalarWhereInput[];
    id?: Prisma.StringFilter<"Cash"> | string;
    balance?:
        | Prisma.DecimalFilter<"Cash">
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    userId?: Prisma.StringFilter<"Cash"> | string;
    createdAt?: Prisma.DateTimeFilter<"Cash"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"Cash"> | Date | string;
};

export type CashCreateWithoutCashesHubInput = {
    id?: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    user: Prisma.UserCreateNestedOneWithoutCashesInput;
};

export type CashUncheckedCreateWithoutCashesHubInput = {
    id?: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    userId: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type CashCreateOrConnectWithoutCashesHubInput = {
    where: Prisma.CashWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.CashCreateWithoutCashesHubInput,
        Prisma.CashUncheckedCreateWithoutCashesHubInput
    >;
};

export type CashUpsertWithoutCashesHubInput = {
    update: Prisma.XOR<
        Prisma.CashUpdateWithoutCashesHubInput,
        Prisma.CashUncheckedUpdateWithoutCashesHubInput
    >;
    create: Prisma.XOR<
        Prisma.CashCreateWithoutCashesHubInput,
        Prisma.CashUncheckedCreateWithoutCashesHubInput
    >;
    where?: Prisma.CashWhereInput;
};

export type CashUpdateToOneWithWhereWithoutCashesHubInput = {
    where?: Prisma.CashWhereInput;
    data: Prisma.XOR<
        Prisma.CashUpdateWithoutCashesHubInput,
        Prisma.CashUncheckedUpdateWithoutCashesHubInput
    >;
};

export type CashUpdateWithoutCashesHubInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    user?: Prisma.UserUpdateOneRequiredWithoutCashesNestedInput;
};

export type CashUncheckedUpdateWithoutCashesHubInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CashCreateManyUserInput = {
    id?: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type CashUpdateWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    cashesHub?: Prisma.CashHubUpdateManyWithoutCashNestedInput;
};

export type CashUncheckedUpdateWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    cashesHub?: Prisma.CashHubUncheckedUpdateManyWithoutCashNestedInput;
};

export type CashUncheckedUpdateManyWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

/**
 * Count Type CashCountOutputType
 */

export type CashCountOutputType = {
    cashesHub: number;
};

export type CashCountOutputTypeSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    cashesHub?: boolean | CashCountOutputTypeCountCashesHubArgs;
};

/**
 * CashCountOutputType without action
 */
export type CashCountOutputTypeDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashCountOutputType
     */
    select?: Prisma.CashCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * CashCountOutputType without action
 */
export type CashCountOutputTypeCountCashesHubArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.CashHubWhereInput;
};

export type CashSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        balance?: boolean;
        userId?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
        cashesHub?: boolean | Prisma.Cash$cashesHubArgs<ExtArgs>;
        _count?: boolean | Prisma.CashCountOutputTypeDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["cash"]
>;

export type CashSelectCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        balance?: boolean;
        userId?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["cash"]
>;

export type CashSelectUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        balance?: boolean;
        userId?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["cash"]
>;

export type CashSelectScalar = {
    id?: boolean;
    balance?: boolean;
    userId?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
};

export type CashOmit<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
    "id" | "balance" | "userId" | "createdAt" | "updatedAt",
    ExtArgs["result"]["cash"]
>;
export type CashInclude<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    cashesHub?: boolean | Prisma.Cash$cashesHubArgs<ExtArgs>;
    _count?: boolean | Prisma.CashCountOutputTypeDefaultArgs<ExtArgs>;
};
export type CashIncludeCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type CashIncludeUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};

export type $CashPayload<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    name: "Cash";
    objects: {
        user: Prisma.$UserPayload<ExtArgs>;
        cashesHub: Prisma.$CashHubPayload<ExtArgs>[];
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: string;
            balance: runtime.Decimal;
            userId: string;
            createdAt: Date;
            updatedAt: Date;
        },
        ExtArgs["result"]["cash"]
    >;
    composites: {};
};

export type CashGetPayload<
    S extends boolean | null | undefined | CashDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$CashPayload, S>;

export type CashCountArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = Omit<CashFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
    select?: CashCountAggregateInputType | true;
};

export interface CashDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: {
        types: Prisma.TypeMap<ExtArgs>["model"]["Cash"];
        meta: { name: "Cash" };
    };
    /**
     * Find zero or one Cash that matches the filter.
     * @param {CashFindUniqueArgs} args - Arguments to find a Cash
     * @example
     * // Get one Cash
     * const cash = await prisma.cash.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends CashFindUniqueArgs>(
        args: Prisma.SelectSubset<T, CashFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__CashClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "findUnique",
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one Cash that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {CashFindUniqueOrThrowArgs} args - Arguments to find a Cash
     * @example
     * // Get one Cash
     * const cash = await prisma.cash.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends CashFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<T, CashFindUniqueOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__CashClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "findUniqueOrThrow",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first Cash that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashFindFirstArgs} args - Arguments to find a Cash
     * @example
     * // Get one Cash
     * const cash = await prisma.cash.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends CashFindFirstArgs>(
        args?: Prisma.SelectSubset<T, CashFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__CashClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "findFirst",
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first Cash that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashFindFirstOrThrowArgs} args - Arguments to find a Cash
     * @example
     * // Get one Cash
     * const cash = await prisma.cash.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends CashFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<T, CashFindFirstOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__CashClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "findFirstOrThrow",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more Cash that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all Cash
     * const cash = await prisma.cash.findMany()
     *
     * // Get first 10 Cash
     * const cash = await prisma.cash.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const cashWithIdOnly = await prisma.cash.findMany({ select: { id: true } })
     *
     */
    findMany<T extends CashFindManyArgs>(
        args?: Prisma.SelectSubset<T, CashFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "findMany",
            GlobalOmitOptions
        >
    >;

    /**
     * Create a Cash.
     * @param {CashCreateArgs} args - Arguments to create a Cash.
     * @example
     * // Create one Cash
     * const Cash = await prisma.cash.create({
     *   data: {
     *     // ... data to create a Cash
     *   }
     * })
     *
     */
    create<T extends CashCreateArgs>(
        args: Prisma.SelectSubset<T, CashCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__CashClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "create",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many Cash.
     * @param {CashCreateManyArgs} args - Arguments to create many Cash.
     * @example
     * // Create many Cash
     * const cash = await prisma.cash.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends CashCreateManyArgs>(
        args?: Prisma.SelectSubset<T, CashCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many Cash and returns the data saved in the database.
     * @param {CashCreateManyAndReturnArgs} args - Arguments to create many Cash.
     * @example
     * // Create many Cash
     * const cash = await prisma.cash.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many Cash and only return the `id`
     * const cashWithIdOnly = await prisma.cash.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends CashCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<T, CashCreateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "createManyAndReturn",
            GlobalOmitOptions
        >
    >;

    /**
     * Delete a Cash.
     * @param {CashDeleteArgs} args - Arguments to delete one Cash.
     * @example
     * // Delete one Cash
     * const Cash = await prisma.cash.delete({
     *   where: {
     *     // ... filter to delete one Cash
     *   }
     * })
     *
     */
    delete<T extends CashDeleteArgs>(
        args: Prisma.SelectSubset<T, CashDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__CashClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "delete",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one Cash.
     * @param {CashUpdateArgs} args - Arguments to update one Cash.
     * @example
     * // Update one Cash
     * const cash = await prisma.cash.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends CashUpdateArgs>(
        args: Prisma.SelectSubset<T, CashUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__CashClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "update",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more Cash.
     * @param {CashDeleteManyArgs} args - Arguments to filter Cash to delete.
     * @example
     * // Delete a few Cash
     * const { count } = await prisma.cash.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends CashDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, CashDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more Cash.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many Cash
     * const cash = await prisma.cash.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends CashUpdateManyArgs>(
        args: Prisma.SelectSubset<T, CashUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more Cash and returns the data updated in the database.
     * @param {CashUpdateManyAndReturnArgs} args - Arguments to update many Cash.
     * @example
     * // Update many Cash
     * const cash = await prisma.cash.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more Cash and only return the `id`
     * const cashWithIdOnly = await prisma.cash.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends CashUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<T, CashUpdateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "updateManyAndReturn",
            GlobalOmitOptions
        >
    >;

    /**
     * Create or update one Cash.
     * @param {CashUpsertArgs} args - Arguments to update or create a Cash.
     * @example
     * // Update or create a Cash
     * const cash = await prisma.cash.upsert({
     *   create: {
     *     // ... data to create a Cash
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the Cash we want to update
     *   }
     * })
     */
    upsert<T extends CashUpsertArgs>(
        args: Prisma.SelectSubset<T, CashUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__CashClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashPayload<ExtArgs>,
            T,
            "upsert",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of Cash.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashCountArgs} args - Arguments to filter Cash to count.
     * @example
     * // Count the number of Cash
     * const count = await prisma.cash.count({
     *   where: {
     *     // ... the filter for the Cash we want to count
     *   }
     * })
     **/
    count<T extends CashCountArgs>(
        args?: Prisma.Subset<T, CashCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<"select", any>
            ? T["select"] extends true
                ? number
                : Prisma.GetScalarType<
                      T["select"],
                      CashCountAggregateOutputType
                  >
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a Cash.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends CashAggregateArgs>(
        args: Prisma.Subset<T, CashAggregateArgs>,
    ): Prisma.PrismaPromise<GetCashAggregateType<T>>;

    /**
     * Group by Cash.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends CashGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<"skip", Prisma.Keys<T>>,
            Prisma.Extends<"take", Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: CashGroupByArgs["orderBy"] }
            : { orderBy?: CashGroupByArgs["orderBy"] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<
            Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
        >,
        ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T["having"]>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
              ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                          : [
                                Error,
                                "Field ",
                                P,
                                ` in "having" needs to be provided in "by"`,
                            ];
                }[HavingFields]
              : "take" extends Prisma.Keys<T>
                ? "orderBy" extends Prisma.Keys<T>
                    ? ByValid extends Prisma.True
                        ? {}
                        : {
                              [P in OrderFields]: P extends ByFields
                                  ? never
                                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                          }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                : "skip" extends Prisma.Keys<T>
                  ? "orderBy" extends Prisma.Keys<T>
                      ? ByValid extends Prisma.True
                          ? {}
                          : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                            }[OrderFields]
                      : 'Error: If you provide "skip", you also need to provide "orderBy"'
                  : ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<T, CashGroupByArgs, OrderByArg> &
            InputErrors,
    ): {} extends InputErrors
        ? GetCashGroupByPayload<T>
        : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the Cash model
     */
    readonly fields: CashFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Cash.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CashClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise";
    user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__UserClient<
        | runtime.Types.Result.GetResult<
              Prisma.$UserPayload<ExtArgs>,
              T,
              "findUniqueOrThrow",
              GlobalOmitOptions
          >
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    cashesHub<T extends Prisma.Cash$cashesHubArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.Cash$cashesHubArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        | runtime.Types.Result.GetResult<
              Prisma.$CashHubPayload<ExtArgs>,
              T,
              "findMany",
              GlobalOmitOptions
          >
        | Null
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?:
            | ((value: T) => TResult1 | PromiseLike<TResult1>)
            | undefined
            | null,
        onrejected?:
            | ((reason: any) => TResult2 | PromiseLike<TResult2>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?:
            | ((reason: any) => TResult | PromiseLike<TResult>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(
        onfinally?: (() => void) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the Cash model
 */
export interface CashFieldRefs {
    readonly id: Prisma.FieldRef<"Cash", "String">;
    readonly balance: Prisma.FieldRef<"Cash", "Decimal">;
    readonly userId: Prisma.FieldRef<"Cash", "String">;
    readonly createdAt: Prisma.FieldRef<"Cash", "DateTime">;
    readonly updatedAt: Prisma.FieldRef<"Cash", "DateTime">;
}

// Custom InputTypes
/**
 * Cash findUnique
 */
export type CashFindUniqueArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashInclude<ExtArgs> | null;
    /**
     * Filter, which Cash to fetch.
     */
    where: Prisma.CashWhereUniqueInput;
};

/**
 * Cash findUniqueOrThrow
 */
export type CashFindUniqueOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashInclude<ExtArgs> | null;
    /**
     * Filter, which Cash to fetch.
     */
    where: Prisma.CashWhereUniqueInput;
};

/**
 * Cash findFirst
 */
export type CashFindFirstArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashInclude<ExtArgs> | null;
    /**
     * Filter, which Cash to fetch.
     */
    where?: Prisma.CashWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Cash to fetch.
     */
    orderBy?:
        | Prisma.CashOrderByWithRelationInput
        | Prisma.CashOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for Cash.
     */
    cursor?: Prisma.CashWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Cash from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Cash.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of Cash.
     */
    distinct?: Prisma.CashScalarFieldEnum | Prisma.CashScalarFieldEnum[];
};

/**
 * Cash findFirstOrThrow
 */
export type CashFindFirstOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashInclude<ExtArgs> | null;
    /**
     * Filter, which Cash to fetch.
     */
    where?: Prisma.CashWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Cash to fetch.
     */
    orderBy?:
        | Prisma.CashOrderByWithRelationInput
        | Prisma.CashOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for Cash.
     */
    cursor?: Prisma.CashWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Cash from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Cash.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of Cash.
     */
    distinct?: Prisma.CashScalarFieldEnum | Prisma.CashScalarFieldEnum[];
};

/**
 * Cash findMany
 */
export type CashFindManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashInclude<ExtArgs> | null;
    /**
     * Filter, which Cash to fetch.
     */
    where?: Prisma.CashWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Cash to fetch.
     */
    orderBy?:
        | Prisma.CashOrderByWithRelationInput
        | Prisma.CashOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing Cash.
     */
    cursor?: Prisma.CashWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Cash from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Cash.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of Cash.
     */
    distinct?: Prisma.CashScalarFieldEnum | Prisma.CashScalarFieldEnum[];
};

/**
 * Cash create
 */
export type CashCreateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashInclude<ExtArgs> | null;
    /**
     * The data needed to create a Cash.
     */
    data: Prisma.XOR<Prisma.CashCreateInput, Prisma.CashUncheckedCreateInput>;
};

/**
 * Cash createMany
 */
export type CashCreateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to create many Cash.
     */
    data: Prisma.CashCreateManyInput | Prisma.CashCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * Cash createManyAndReturn
 */
export type CashCreateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * The data used to create many Cash.
     */
    data: Prisma.CashCreateManyInput | Prisma.CashCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * Cash update
 */
export type CashUpdateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashInclude<ExtArgs> | null;
    /**
     * The data needed to update a Cash.
     */
    data: Prisma.XOR<Prisma.CashUpdateInput, Prisma.CashUncheckedUpdateInput>;
    /**
     * Choose, which Cash to update.
     */
    where: Prisma.CashWhereUniqueInput;
};

/**
 * Cash updateMany
 */
export type CashUpdateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to update Cash.
     */
    data: Prisma.XOR<
        Prisma.CashUpdateManyMutationInput,
        Prisma.CashUncheckedUpdateManyInput
    >;
    /**
     * Filter which Cash to update
     */
    where?: Prisma.CashWhereInput;
    /**
     * Limit how many Cash to update.
     */
    limit?: number;
};

/**
 * Cash updateManyAndReturn
 */
export type CashUpdateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * The data used to update Cash.
     */
    data: Prisma.XOR<
        Prisma.CashUpdateManyMutationInput,
        Prisma.CashUncheckedUpdateManyInput
    >;
    /**
     * Filter which Cash to update
     */
    where?: Prisma.CashWhereInput;
    /**
     * Limit how many Cash to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * Cash upsert
 */
export type CashUpsertArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashInclude<ExtArgs> | null;
    /**
     * The filter to search for the Cash to update in case it exists.
     */
    where: Prisma.CashWhereUniqueInput;
    /**
     * In case the Cash found by the `where` argument doesn't exist, create a new Cash with this data.
     */
    create: Prisma.XOR<Prisma.CashCreateInput, Prisma.CashUncheckedCreateInput>;
    /**
     * In case the Cash was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<Prisma.CashUpdateInput, Prisma.CashUncheckedUpdateInput>;
};

/**
 * Cash delete
 */
export type CashDeleteArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashInclude<ExtArgs> | null;
    /**
     * Filter which Cash to delete.
     */
    where: Prisma.CashWhereUniqueInput;
};

/**
 * Cash deleteMany
 */
export type CashDeleteManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which Cash to delete
     */
    where?: Prisma.CashWhereInput;
    /**
     * Limit how many Cash to delete.
     */
    limit?: number;
};

/**
 * Cash.cashesHub
 */
export type Cash$cashesHubArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
    where?: Prisma.CashHubWhereInput;
    orderBy?:
        | Prisma.CashHubOrderByWithRelationInput
        | Prisma.CashHubOrderByWithRelationInput[];
    cursor?: Prisma.CashHubWhereUniqueInput;
    take?: number;
    skip?: number;
    distinct?: Prisma.CashHubScalarFieldEnum | Prisma.CashHubScalarFieldEnum[];
};

/**
 * Cash without action
 */
export type CashDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Cash
     */
    select?: Prisma.CashSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Cash
     */
    omit?: Prisma.CashOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashInclude<ExtArgs> | null;
};
