/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `CashHub` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.js";
import type * as Prisma from "../internal/prismaNamespace.js";

/**
 * Model CashHub
 *
 */
export type CashHubModel =
    runtime.Types.Result.DefaultSelection<Prisma.$CashHubPayload>;

export type AggregateCashHub = {
    _count: CashHubCountAggregateOutputType | null;
    _avg: CashHubAvgAggregateOutputType | null;
    _sum: CashHubSumAggregateOutputType | null;
    _min: CashHubMinAggregateOutputType | null;
    _max: CashHubMaxAggregateOutputType | null;
};

export type CashHubAvgAggregateOutputType = {
    balance: runtime.Decimal | null;
};

export type CashHubSumAggregateOutputType = {
    balance: runtime.Decimal | null;
};

export type CashHubMinAggregateOutputType = {
    id: string | null;
    name: string | null;
    description: string | null;
    balance: runtime.Decimal | null;
    cashId: string | null;
    createdAt: Date | null;
    updatedAt: Date | null;
};

export type CashHubMaxAggregateOutputType = {
    id: string | null;
    name: string | null;
    description: string | null;
    balance: runtime.Decimal | null;
    cashId: string | null;
    createdAt: Date | null;
    updatedAt: Date | null;
};

export type CashHubCountAggregateOutputType = {
    id: number;
    name: number;
    description: number;
    balance: number;
    cashId: number;
    createdAt: number;
    updatedAt: number;
    _all: number;
};

export type CashHubAvgAggregateInputType = {
    balance?: true;
};

export type CashHubSumAggregateInputType = {
    balance?: true;
};

export type CashHubMinAggregateInputType = {
    id?: true;
    name?: true;
    description?: true;
    balance?: true;
    cashId?: true;
    createdAt?: true;
    updatedAt?: true;
};

export type CashHubMaxAggregateInputType = {
    id?: true;
    name?: true;
    description?: true;
    balance?: true;
    cashId?: true;
    createdAt?: true;
    updatedAt?: true;
};

export type CashHubCountAggregateInputType = {
    id?: true;
    name?: true;
    description?: true;
    balance?: true;
    cashId?: true;
    createdAt?: true;
    updatedAt?: true;
    _all?: true;
};

export type CashHubAggregateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which CashHub to aggregate.
     */
    where?: Prisma.CashHubWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CashHubs to fetch.
     */
    orderBy?:
        | Prisma.CashHubOrderByWithRelationInput
        | Prisma.CashHubOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.CashHubWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CashHubs from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CashHubs.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned CashHubs
     **/
    _count?: true | CashHubCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to average
     **/
    _avg?: CashHubAvgAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to sum
     **/
    _sum?: CashHubSumAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: CashHubMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: CashHubMaxAggregateInputType;
};

export type GetCashHubAggregateType<T extends CashHubAggregateArgs> = {
    [P in keyof T & keyof AggregateCashHub]: P extends "_count" | "count"
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateCashHub[P]>
        : Prisma.GetScalarType<T[P], AggregateCashHub[P]>;
};

export type CashHubGroupByArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.CashHubWhereInput;
    orderBy?:
        | Prisma.CashHubOrderByWithAggregationInput
        | Prisma.CashHubOrderByWithAggregationInput[];
    by: Prisma.CashHubScalarFieldEnum[] | Prisma.CashHubScalarFieldEnum;
    having?: Prisma.CashHubScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: CashHubCountAggregateInputType | true;
    _avg?: CashHubAvgAggregateInputType;
    _sum?: CashHubSumAggregateInputType;
    _min?: CashHubMinAggregateInputType;
    _max?: CashHubMaxAggregateInputType;
};

export type CashHubGroupByOutputType = {
    id: string;
    name: string;
    description: string;
    balance: runtime.Decimal;
    cashId: string;
    createdAt: Date;
    updatedAt: Date;
    _count: CashHubCountAggregateOutputType | null;
    _avg: CashHubAvgAggregateOutputType | null;
    _sum: CashHubSumAggregateOutputType | null;
    _min: CashHubMinAggregateOutputType | null;
    _max: CashHubMaxAggregateOutputType | null;
};

export type GetCashHubGroupByPayload<T extends CashHubGroupByArgs> =
    Prisma.PrismaPromise<
        Array<
            Prisma.PickEnumerable<CashHubGroupByOutputType, T["by"]> & {
                [P in keyof T &
                    keyof CashHubGroupByOutputType]: P extends "_count"
                    ? T[P] extends boolean
                        ? number
                        : Prisma.GetScalarType<
                              T[P],
                              CashHubGroupByOutputType[P]
                          >
                    : Prisma.GetScalarType<T[P], CashHubGroupByOutputType[P]>;
            }
        >
    >;

export type CashHubWhereInput = {
    AND?: Prisma.CashHubWhereInput | Prisma.CashHubWhereInput[];
    OR?: Prisma.CashHubWhereInput[];
    NOT?: Prisma.CashHubWhereInput | Prisma.CashHubWhereInput[];
    id?: Prisma.StringFilter<"CashHub"> | string;
    name?: Prisma.StringFilter<"CashHub"> | string;
    description?: Prisma.StringFilter<"CashHub"> | string;
    balance?:
        | Prisma.DecimalFilter<"CashHub">
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    cashId?: Prisma.StringFilter<"CashHub"> | string;
    createdAt?: Prisma.DateTimeFilter<"CashHub"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"CashHub"> | Date | string;
    cash?: Prisma.XOR<Prisma.CashScalarRelationFilter, Prisma.CashWhereInput>;
};

export type CashHubOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    name?: Prisma.SortOrder;
    description?: Prisma.SortOrder;
    balance?: Prisma.SortOrder;
    cashId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    cash?: Prisma.CashOrderByWithRelationInput;
};

export type CashHubWhereUniqueInput = Prisma.AtLeast<
    {
        id?: string;
        AND?: Prisma.CashHubWhereInput | Prisma.CashHubWhereInput[];
        OR?: Prisma.CashHubWhereInput[];
        NOT?: Prisma.CashHubWhereInput | Prisma.CashHubWhereInput[];
        name?: Prisma.StringFilter<"CashHub"> | string;
        description?: Prisma.StringFilter<"CashHub"> | string;
        balance?:
            | Prisma.DecimalFilter<"CashHub">
            | runtime.Decimal
            | runtime.DecimalJsLike
            | number
            | string;
        cashId?: Prisma.StringFilter<"CashHub"> | string;
        createdAt?: Prisma.DateTimeFilter<"CashHub"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"CashHub"> | Date | string;
        cash?: Prisma.XOR<
            Prisma.CashScalarRelationFilter,
            Prisma.CashWhereInput
        >;
    },
    "id"
>;

export type CashHubOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    name?: Prisma.SortOrder;
    description?: Prisma.SortOrder;
    balance?: Prisma.SortOrder;
    cashId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    _count?: Prisma.CashHubCountOrderByAggregateInput;
    _avg?: Prisma.CashHubAvgOrderByAggregateInput;
    _max?: Prisma.CashHubMaxOrderByAggregateInput;
    _min?: Prisma.CashHubMinOrderByAggregateInput;
    _sum?: Prisma.CashHubSumOrderByAggregateInput;
};

export type CashHubScalarWhereWithAggregatesInput = {
    AND?:
        | Prisma.CashHubScalarWhereWithAggregatesInput
        | Prisma.CashHubScalarWhereWithAggregatesInput[];
    OR?: Prisma.CashHubScalarWhereWithAggregatesInput[];
    NOT?:
        | Prisma.CashHubScalarWhereWithAggregatesInput
        | Prisma.CashHubScalarWhereWithAggregatesInput[];
    id?: Prisma.StringWithAggregatesFilter<"CashHub"> | string;
    name?: Prisma.StringWithAggregatesFilter<"CashHub"> | string;
    description?: Prisma.StringWithAggregatesFilter<"CashHub"> | string;
    balance?:
        | Prisma.DecimalWithAggregatesFilter<"CashHub">
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    cashId?: Prisma.StringWithAggregatesFilter<"CashHub"> | string;
    createdAt?: Prisma.DateTimeWithAggregatesFilter<"CashHub"> | Date | string;
    updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CashHub"> | Date | string;
};

export type CashHubCreateInput = {
    id?: string;
    name: string;
    description: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    cash: Prisma.CashCreateNestedOneWithoutCashesHubInput;
};

export type CashHubUncheckedCreateInput = {
    id?: string;
    name: string;
    description: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    cashId: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type CashHubUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    cash?: Prisma.CashUpdateOneRequiredWithoutCashesHubNestedInput;
};

export type CashHubUncheckedUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    cashId?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CashHubCreateManyInput = {
    id?: string;
    name: string;
    description: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    cashId: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type CashHubUpdateManyMutationInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CashHubUncheckedUpdateManyInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    cashId?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CashHubListRelationFilter = {
    every?: Prisma.CashHubWhereInput;
    some?: Prisma.CashHubWhereInput;
    none?: Prisma.CashHubWhereInput;
};

export type CashHubOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder;
};

export type CashHubCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    name?: Prisma.SortOrder;
    description?: Prisma.SortOrder;
    balance?: Prisma.SortOrder;
    cashId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type CashHubAvgOrderByAggregateInput = {
    balance?: Prisma.SortOrder;
};

export type CashHubMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    name?: Prisma.SortOrder;
    description?: Prisma.SortOrder;
    balance?: Prisma.SortOrder;
    cashId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type CashHubMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    name?: Prisma.SortOrder;
    description?: Prisma.SortOrder;
    balance?: Prisma.SortOrder;
    cashId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type CashHubSumOrderByAggregateInput = {
    balance?: Prisma.SortOrder;
};

export type CashHubCreateNestedManyWithoutCashInput = {
    create?:
        | Prisma.XOR<
              Prisma.CashHubCreateWithoutCashInput,
              Prisma.CashHubUncheckedCreateWithoutCashInput
          >
        | Prisma.CashHubCreateWithoutCashInput[]
        | Prisma.CashHubUncheckedCreateWithoutCashInput[];
    connectOrCreate?:
        | Prisma.CashHubCreateOrConnectWithoutCashInput
        | Prisma.CashHubCreateOrConnectWithoutCashInput[];
    createMany?: Prisma.CashHubCreateManyCashInputEnvelope;
    connect?: Prisma.CashHubWhereUniqueInput | Prisma.CashHubWhereUniqueInput[];
};

export type CashHubUncheckedCreateNestedManyWithoutCashInput = {
    create?:
        | Prisma.XOR<
              Prisma.CashHubCreateWithoutCashInput,
              Prisma.CashHubUncheckedCreateWithoutCashInput
          >
        | Prisma.CashHubCreateWithoutCashInput[]
        | Prisma.CashHubUncheckedCreateWithoutCashInput[];
    connectOrCreate?:
        | Prisma.CashHubCreateOrConnectWithoutCashInput
        | Prisma.CashHubCreateOrConnectWithoutCashInput[];
    createMany?: Prisma.CashHubCreateManyCashInputEnvelope;
    connect?: Prisma.CashHubWhereUniqueInput | Prisma.CashHubWhereUniqueInput[];
};

export type CashHubUpdateManyWithoutCashNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.CashHubCreateWithoutCashInput,
              Prisma.CashHubUncheckedCreateWithoutCashInput
          >
        | Prisma.CashHubCreateWithoutCashInput[]
        | Prisma.CashHubUncheckedCreateWithoutCashInput[];
    connectOrCreate?:
        | Prisma.CashHubCreateOrConnectWithoutCashInput
        | Prisma.CashHubCreateOrConnectWithoutCashInput[];
    upsert?:
        | Prisma.CashHubUpsertWithWhereUniqueWithoutCashInput
        | Prisma.CashHubUpsertWithWhereUniqueWithoutCashInput[];
    createMany?: Prisma.CashHubCreateManyCashInputEnvelope;
    set?: Prisma.CashHubWhereUniqueInput | Prisma.CashHubWhereUniqueInput[];
    disconnect?:
        | Prisma.CashHubWhereUniqueInput
        | Prisma.CashHubWhereUniqueInput[];
    delete?: Prisma.CashHubWhereUniqueInput | Prisma.CashHubWhereUniqueInput[];
    connect?: Prisma.CashHubWhereUniqueInput | Prisma.CashHubWhereUniqueInput[];
    update?:
        | Prisma.CashHubUpdateWithWhereUniqueWithoutCashInput
        | Prisma.CashHubUpdateWithWhereUniqueWithoutCashInput[];
    updateMany?:
        | Prisma.CashHubUpdateManyWithWhereWithoutCashInput
        | Prisma.CashHubUpdateManyWithWhereWithoutCashInput[];
    deleteMany?:
        | Prisma.CashHubScalarWhereInput
        | Prisma.CashHubScalarWhereInput[];
};

export type CashHubUncheckedUpdateManyWithoutCashNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.CashHubCreateWithoutCashInput,
              Prisma.CashHubUncheckedCreateWithoutCashInput
          >
        | Prisma.CashHubCreateWithoutCashInput[]
        | Prisma.CashHubUncheckedCreateWithoutCashInput[];
    connectOrCreate?:
        | Prisma.CashHubCreateOrConnectWithoutCashInput
        | Prisma.CashHubCreateOrConnectWithoutCashInput[];
    upsert?:
        | Prisma.CashHubUpsertWithWhereUniqueWithoutCashInput
        | Prisma.CashHubUpsertWithWhereUniqueWithoutCashInput[];
    createMany?: Prisma.CashHubCreateManyCashInputEnvelope;
    set?: Prisma.CashHubWhereUniqueInput | Prisma.CashHubWhereUniqueInput[];
    disconnect?:
        | Prisma.CashHubWhereUniqueInput
        | Prisma.CashHubWhereUniqueInput[];
    delete?: Prisma.CashHubWhereUniqueInput | Prisma.CashHubWhereUniqueInput[];
    connect?: Prisma.CashHubWhereUniqueInput | Prisma.CashHubWhereUniqueInput[];
    update?:
        | Prisma.CashHubUpdateWithWhereUniqueWithoutCashInput
        | Prisma.CashHubUpdateWithWhereUniqueWithoutCashInput[];
    updateMany?:
        | Prisma.CashHubUpdateManyWithWhereWithoutCashInput
        | Prisma.CashHubUpdateManyWithWhereWithoutCashInput[];
    deleteMany?:
        | Prisma.CashHubScalarWhereInput
        | Prisma.CashHubScalarWhereInput[];
};

export type CashHubCreateWithoutCashInput = {
    id?: string;
    name: string;
    description: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type CashHubUncheckedCreateWithoutCashInput = {
    id?: string;
    name: string;
    description: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type CashHubCreateOrConnectWithoutCashInput = {
    where: Prisma.CashHubWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.CashHubCreateWithoutCashInput,
        Prisma.CashHubUncheckedCreateWithoutCashInput
    >;
};

export type CashHubCreateManyCashInputEnvelope = {
    data:
        | Prisma.CashHubCreateManyCashInput
        | Prisma.CashHubCreateManyCashInput[];
    skipDuplicates?: boolean;
};

export type CashHubUpsertWithWhereUniqueWithoutCashInput = {
    where: Prisma.CashHubWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.CashHubUpdateWithoutCashInput,
        Prisma.CashHubUncheckedUpdateWithoutCashInput
    >;
    create: Prisma.XOR<
        Prisma.CashHubCreateWithoutCashInput,
        Prisma.CashHubUncheckedCreateWithoutCashInput
    >;
};

export type CashHubUpdateWithWhereUniqueWithoutCashInput = {
    where: Prisma.CashHubWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.CashHubUpdateWithoutCashInput,
        Prisma.CashHubUncheckedUpdateWithoutCashInput
    >;
};

export type CashHubUpdateManyWithWhereWithoutCashInput = {
    where: Prisma.CashHubScalarWhereInput;
    data: Prisma.XOR<
        Prisma.CashHubUpdateManyMutationInput,
        Prisma.CashHubUncheckedUpdateManyWithoutCashInput
    >;
};

export type CashHubScalarWhereInput = {
    AND?: Prisma.CashHubScalarWhereInput | Prisma.CashHubScalarWhereInput[];
    OR?: Prisma.CashHubScalarWhereInput[];
    NOT?: Prisma.CashHubScalarWhereInput | Prisma.CashHubScalarWhereInput[];
    id?: Prisma.StringFilter<"CashHub"> | string;
    name?: Prisma.StringFilter<"CashHub"> | string;
    description?: Prisma.StringFilter<"CashHub"> | string;
    balance?:
        | Prisma.DecimalFilter<"CashHub">
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    cashId?: Prisma.StringFilter<"CashHub"> | string;
    createdAt?: Prisma.DateTimeFilter<"CashHub"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"CashHub"> | Date | string;
};

export type CashHubCreateManyCashInput = {
    id?: string;
    name: string;
    description: string;
    balance: runtime.Decimal | runtime.DecimalJsLike | number | string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type CashHubUpdateWithoutCashInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CashHubUncheckedUpdateWithoutCashInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CashHubUncheckedUpdateManyWithoutCashInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    name?: Prisma.StringFieldUpdateOperationsInput | string;
    description?: Prisma.StringFieldUpdateOperationsInput | string;
    balance?:
        | Prisma.DecimalFieldUpdateOperationsInput
        | runtime.Decimal
        | runtime.DecimalJsLike
        | number
        | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type CashHubSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        name?: boolean;
        description?: boolean;
        balance?: boolean;
        cashId?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        cash?: boolean | Prisma.CashDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["cashHub"]
>;

export type CashHubSelectCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        name?: boolean;
        description?: boolean;
        balance?: boolean;
        cashId?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        cash?: boolean | Prisma.CashDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["cashHub"]
>;

export type CashHubSelectUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        name?: boolean;
        description?: boolean;
        balance?: boolean;
        cashId?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        cash?: boolean | Prisma.CashDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["cashHub"]
>;

export type CashHubSelectScalar = {
    id?: boolean;
    name?: boolean;
    description?: boolean;
    balance?: boolean;
    cashId?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
};

export type CashHubOmit<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
    | "id"
    | "name"
    | "description"
    | "balance"
    | "cashId"
    | "createdAt"
    | "updatedAt",
    ExtArgs["result"]["cashHub"]
>;
export type CashHubInclude<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    cash?: boolean | Prisma.CashDefaultArgs<ExtArgs>;
};
export type CashHubIncludeCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    cash?: boolean | Prisma.CashDefaultArgs<ExtArgs>;
};
export type CashHubIncludeUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    cash?: boolean | Prisma.CashDefaultArgs<ExtArgs>;
};

export type $CashHubPayload<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    name: "CashHub";
    objects: {
        cash: Prisma.$CashPayload<ExtArgs>;
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: string;
            name: string;
            description: string;
            balance: runtime.Decimal;
            cashId: string;
            createdAt: Date;
            updatedAt: Date;
        },
        ExtArgs["result"]["cashHub"]
    >;
    composites: {};
};

export type CashHubGetPayload<
    S extends boolean | null | undefined | CashHubDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$CashHubPayload, S>;

export type CashHubCountArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = Omit<CashHubFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
    select?: CashHubCountAggregateInputType | true;
};

export interface CashHubDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: {
        types: Prisma.TypeMap<ExtArgs>["model"]["CashHub"];
        meta: { name: "CashHub" };
    };
    /**
     * Find zero or one CashHub that matches the filter.
     * @param {CashHubFindUniqueArgs} args - Arguments to find a CashHub
     * @example
     * // Get one CashHub
     * const cashHub = await prisma.cashHub.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends CashHubFindUniqueArgs>(
        args: Prisma.SelectSubset<T, CashHubFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__CashHubClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "findUnique",
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one CashHub that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {CashHubFindUniqueOrThrowArgs} args - Arguments to find a CashHub
     * @example
     * // Get one CashHub
     * const cashHub = await prisma.cashHub.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends CashHubFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<T, CashHubFindUniqueOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__CashHubClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "findUniqueOrThrow",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first CashHub that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashHubFindFirstArgs} args - Arguments to find a CashHub
     * @example
     * // Get one CashHub
     * const cashHub = await prisma.cashHub.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends CashHubFindFirstArgs>(
        args?: Prisma.SelectSubset<T, CashHubFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__CashHubClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "findFirst",
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first CashHub that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashHubFindFirstOrThrowArgs} args - Arguments to find a CashHub
     * @example
     * // Get one CashHub
     * const cashHub = await prisma.cashHub.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends CashHubFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<T, CashHubFindFirstOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__CashHubClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "findFirstOrThrow",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more CashHubs that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashHubFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all CashHubs
     * const cashHubs = await prisma.cashHub.findMany()
     *
     * // Get first 10 CashHubs
     * const cashHubs = await prisma.cashHub.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const cashHubWithIdOnly = await prisma.cashHub.findMany({ select: { id: true } })
     *
     */
    findMany<T extends CashHubFindManyArgs>(
        args?: Prisma.SelectSubset<T, CashHubFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "findMany",
            GlobalOmitOptions
        >
    >;

    /**
     * Create a CashHub.
     * @param {CashHubCreateArgs} args - Arguments to create a CashHub.
     * @example
     * // Create one CashHub
     * const CashHub = await prisma.cashHub.create({
     *   data: {
     *     // ... data to create a CashHub
     *   }
     * })
     *
     */
    create<T extends CashHubCreateArgs>(
        args: Prisma.SelectSubset<T, CashHubCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__CashHubClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "create",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many CashHubs.
     * @param {CashHubCreateManyArgs} args - Arguments to create many CashHubs.
     * @example
     * // Create many CashHubs
     * const cashHub = await prisma.cashHub.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends CashHubCreateManyArgs>(
        args?: Prisma.SelectSubset<T, CashHubCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many CashHubs and returns the data saved in the database.
     * @param {CashHubCreateManyAndReturnArgs} args - Arguments to create many CashHubs.
     * @example
     * // Create many CashHubs
     * const cashHub = await prisma.cashHub.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many CashHubs and only return the `id`
     * const cashHubWithIdOnly = await prisma.cashHub.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends CashHubCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<T, CashHubCreateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "createManyAndReturn",
            GlobalOmitOptions
        >
    >;

    /**
     * Delete a CashHub.
     * @param {CashHubDeleteArgs} args - Arguments to delete one CashHub.
     * @example
     * // Delete one CashHub
     * const CashHub = await prisma.cashHub.delete({
     *   where: {
     *     // ... filter to delete one CashHub
     *   }
     * })
     *
     */
    delete<T extends CashHubDeleteArgs>(
        args: Prisma.SelectSubset<T, CashHubDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__CashHubClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "delete",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one CashHub.
     * @param {CashHubUpdateArgs} args - Arguments to update one CashHub.
     * @example
     * // Update one CashHub
     * const cashHub = await prisma.cashHub.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends CashHubUpdateArgs>(
        args: Prisma.SelectSubset<T, CashHubUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__CashHubClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "update",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more CashHubs.
     * @param {CashHubDeleteManyArgs} args - Arguments to filter CashHubs to delete.
     * @example
     * // Delete a few CashHubs
     * const { count } = await prisma.cashHub.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends CashHubDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, CashHubDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more CashHubs.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashHubUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many CashHubs
     * const cashHub = await prisma.cashHub.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends CashHubUpdateManyArgs>(
        args: Prisma.SelectSubset<T, CashHubUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more CashHubs and returns the data updated in the database.
     * @param {CashHubUpdateManyAndReturnArgs} args - Arguments to update many CashHubs.
     * @example
     * // Update many CashHubs
     * const cashHub = await prisma.cashHub.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more CashHubs and only return the `id`
     * const cashHubWithIdOnly = await prisma.cashHub.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends CashHubUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<T, CashHubUpdateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "updateManyAndReturn",
            GlobalOmitOptions
        >
    >;

    /**
     * Create or update one CashHub.
     * @param {CashHubUpsertArgs} args - Arguments to update or create a CashHub.
     * @example
     * // Update or create a CashHub
     * const cashHub = await prisma.cashHub.upsert({
     *   create: {
     *     // ... data to create a CashHub
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the CashHub we want to update
     *   }
     * })
     */
    upsert<T extends CashHubUpsertArgs>(
        args: Prisma.SelectSubset<T, CashHubUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__CashHubClient<
        runtime.Types.Result.GetResult<
            Prisma.$CashHubPayload<ExtArgs>,
            T,
            "upsert",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of CashHubs.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashHubCountArgs} args - Arguments to filter CashHubs to count.
     * @example
     * // Count the number of CashHubs
     * const count = await prisma.cashHub.count({
     *   where: {
     *     // ... the filter for the CashHubs we want to count
     *   }
     * })
     **/
    count<T extends CashHubCountArgs>(
        args?: Prisma.Subset<T, CashHubCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<"select", any>
            ? T["select"] extends true
                ? number
                : Prisma.GetScalarType<
                      T["select"],
                      CashHubCountAggregateOutputType
                  >
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a CashHub.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashHubAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends CashHubAggregateArgs>(
        args: Prisma.Subset<T, CashHubAggregateArgs>,
    ): Prisma.PrismaPromise<GetCashHubAggregateType<T>>;

    /**
     * Group by CashHub.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {CashHubGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends CashHubGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<"skip", Prisma.Keys<T>>,
            Prisma.Extends<"take", Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: CashHubGroupByArgs["orderBy"] }
            : { orderBy?: CashHubGroupByArgs["orderBy"] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<
            Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
        >,
        ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T["having"]>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
              ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                          : [
                                Error,
                                "Field ",
                                P,
                                ` in "having" needs to be provided in "by"`,
                            ];
                }[HavingFields]
              : "take" extends Prisma.Keys<T>
                ? "orderBy" extends Prisma.Keys<T>
                    ? ByValid extends Prisma.True
                        ? {}
                        : {
                              [P in OrderFields]: P extends ByFields
                                  ? never
                                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                          }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                : "skip" extends Prisma.Keys<T>
                  ? "orderBy" extends Prisma.Keys<T>
                      ? ByValid extends Prisma.True
                          ? {}
                          : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                            }[OrderFields]
                      : 'Error: If you provide "skip", you also need to provide "orderBy"'
                  : ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<T, CashHubGroupByArgs, OrderByArg> &
            InputErrors,
    ): {} extends InputErrors
        ? GetCashHubGroupByPayload<T>
        : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the CashHub model
     */
    readonly fields: CashHubFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CashHub.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CashHubClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise";
    cash<T extends Prisma.CashDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.CashDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__CashClient<
        | runtime.Types.Result.GetResult<
              Prisma.$CashPayload<ExtArgs>,
              T,
              "findUniqueOrThrow",
              GlobalOmitOptions
          >
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?:
            | ((value: T) => TResult1 | PromiseLike<TResult1>)
            | undefined
            | null,
        onrejected?:
            | ((reason: any) => TResult2 | PromiseLike<TResult2>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?:
            | ((reason: any) => TResult | PromiseLike<TResult>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(
        onfinally?: (() => void) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the CashHub model
 */
export interface CashHubFieldRefs {
    readonly id: Prisma.FieldRef<"CashHub", "String">;
    readonly name: Prisma.FieldRef<"CashHub", "String">;
    readonly description: Prisma.FieldRef<"CashHub", "String">;
    readonly balance: Prisma.FieldRef<"CashHub", "Decimal">;
    readonly cashId: Prisma.FieldRef<"CashHub", "String">;
    readonly createdAt: Prisma.FieldRef<"CashHub", "DateTime">;
    readonly updatedAt: Prisma.FieldRef<"CashHub", "DateTime">;
}

// Custom InputTypes
/**
 * CashHub findUnique
 */
export type CashHubFindUniqueArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
    /**
     * Filter, which CashHub to fetch.
     */
    where: Prisma.CashHubWhereUniqueInput;
};

/**
 * CashHub findUniqueOrThrow
 */
export type CashHubFindUniqueOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
    /**
     * Filter, which CashHub to fetch.
     */
    where: Prisma.CashHubWhereUniqueInput;
};

/**
 * CashHub findFirst
 */
export type CashHubFindFirstArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
    /**
     * Filter, which CashHub to fetch.
     */
    where?: Prisma.CashHubWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CashHubs to fetch.
     */
    orderBy?:
        | Prisma.CashHubOrderByWithRelationInput
        | Prisma.CashHubOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for CashHubs.
     */
    cursor?: Prisma.CashHubWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CashHubs from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CashHubs.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of CashHubs.
     */
    distinct?: Prisma.CashHubScalarFieldEnum | Prisma.CashHubScalarFieldEnum[];
};

/**
 * CashHub findFirstOrThrow
 */
export type CashHubFindFirstOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
    /**
     * Filter, which CashHub to fetch.
     */
    where?: Prisma.CashHubWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CashHubs to fetch.
     */
    orderBy?:
        | Prisma.CashHubOrderByWithRelationInput
        | Prisma.CashHubOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for CashHubs.
     */
    cursor?: Prisma.CashHubWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CashHubs from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CashHubs.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of CashHubs.
     */
    distinct?: Prisma.CashHubScalarFieldEnum | Prisma.CashHubScalarFieldEnum[];
};

/**
 * CashHub findMany
 */
export type CashHubFindManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
    /**
     * Filter, which CashHubs to fetch.
     */
    where?: Prisma.CashHubWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of CashHubs to fetch.
     */
    orderBy?:
        | Prisma.CashHubOrderByWithRelationInput
        | Prisma.CashHubOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing CashHubs.
     */
    cursor?: Prisma.CashHubWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` CashHubs from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` CashHubs.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of CashHubs.
     */
    distinct?: Prisma.CashHubScalarFieldEnum | Prisma.CashHubScalarFieldEnum[];
};

/**
 * CashHub create
 */
export type CashHubCreateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
    /**
     * The data needed to create a CashHub.
     */
    data: Prisma.XOR<
        Prisma.CashHubCreateInput,
        Prisma.CashHubUncheckedCreateInput
    >;
};

/**
 * CashHub createMany
 */
export type CashHubCreateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to create many CashHubs.
     */
    data: Prisma.CashHubCreateManyInput | Prisma.CashHubCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * CashHub createManyAndReturn
 */
export type CashHubCreateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * The data used to create many CashHubs.
     */
    data: Prisma.CashHubCreateManyInput | Prisma.CashHubCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * CashHub update
 */
export type CashHubUpdateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
    /**
     * The data needed to update a CashHub.
     */
    data: Prisma.XOR<
        Prisma.CashHubUpdateInput,
        Prisma.CashHubUncheckedUpdateInput
    >;
    /**
     * Choose, which CashHub to update.
     */
    where: Prisma.CashHubWhereUniqueInput;
};

/**
 * CashHub updateMany
 */
export type CashHubUpdateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to update CashHubs.
     */
    data: Prisma.XOR<
        Prisma.CashHubUpdateManyMutationInput,
        Prisma.CashHubUncheckedUpdateManyInput
    >;
    /**
     * Filter which CashHubs to update
     */
    where?: Prisma.CashHubWhereInput;
    /**
     * Limit how many CashHubs to update.
     */
    limit?: number;
};

/**
 * CashHub updateManyAndReturn
 */
export type CashHubUpdateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * The data used to update CashHubs.
     */
    data: Prisma.XOR<
        Prisma.CashHubUpdateManyMutationInput,
        Prisma.CashHubUncheckedUpdateManyInput
    >;
    /**
     * Filter which CashHubs to update
     */
    where?: Prisma.CashHubWhereInput;
    /**
     * Limit how many CashHubs to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * CashHub upsert
 */
export type CashHubUpsertArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
    /**
     * The filter to search for the CashHub to update in case it exists.
     */
    where: Prisma.CashHubWhereUniqueInput;
    /**
     * In case the CashHub found by the `where` argument doesn't exist, create a new CashHub with this data.
     */
    create: Prisma.XOR<
        Prisma.CashHubCreateInput,
        Prisma.CashHubUncheckedCreateInput
    >;
    /**
     * In case the CashHub was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<
        Prisma.CashHubUpdateInput,
        Prisma.CashHubUncheckedUpdateInput
    >;
};

/**
 * CashHub delete
 */
export type CashHubDeleteArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
    /**
     * Filter which CashHub to delete.
     */
    where: Prisma.CashHubWhereUniqueInput;
};

/**
 * CashHub deleteMany
 */
export type CashHubDeleteManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which CashHubs to delete
     */
    where?: Prisma.CashHubWhereInput;
    /**
     * Limit how many CashHubs to delete.
     */
    limit?: number;
};

/**
 * CashHub without action
 */
export type CashHubDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the CashHub
     */
    select?: Prisma.CashHubSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the CashHub
     */
    omit?: Prisma.CashHubOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.CashHubInclude<ExtArgs> | null;
};
