/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Faith` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.ts";
import type * as Prisma from "../internal/prismaNamespace.ts";

/**
 * Model Faith
 *
 */
export type FaithModel =
    runtime.Types.Result.DefaultSelection<Prisma.$FaithPayload>;

export type AggregateFaith = {
    _count: FaithCountAggregateOutputType | null;
    _min: FaithMinAggregateOutputType | null;
    _max: FaithMaxAggregateOutputType | null;
};

export type FaithMinAggregateOutputType = {
    id: string | null;
    church: string | null;
    userId: string | null;
    createdAt: Date | null;
    updatedAt: Date | null;
};

export type FaithMaxAggregateOutputType = {
    id: string | null;
    church: string | null;
    userId: string | null;
    createdAt: Date | null;
    updatedAt: Date | null;
};

export type FaithCountAggregateOutputType = {
    id: number;
    church: number;
    userId: number;
    createdAt: number;
    updatedAt: number;
    _all: number;
};

export type FaithMinAggregateInputType = {
    id?: true;
    church?: true;
    userId?: true;
    createdAt?: true;
    updatedAt?: true;
};

export type FaithMaxAggregateInputType = {
    id?: true;
    church?: true;
    userId?: true;
    createdAt?: true;
    updatedAt?: true;
};

export type FaithCountAggregateInputType = {
    id?: true;
    church?: true;
    userId?: true;
    createdAt?: true;
    updatedAt?: true;
    _all?: true;
};

export type FaithAggregateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which Faith to aggregate.
     */
    where?: Prisma.FaithWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Faiths to fetch.
     */
    orderBy?:
        | Prisma.FaithOrderByWithRelationInput
        | Prisma.FaithOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the start position
     */
    cursor?: Prisma.FaithWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Faiths from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Faiths.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Count returned Faiths
     **/
    _count?: true | FaithCountAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the minimum value
     **/
    _min?: FaithMinAggregateInputType;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
     *
     * Select which fields to find the maximum value
     **/
    _max?: FaithMaxAggregateInputType;
};

export type GetFaithAggregateType<T extends FaithAggregateArgs> = {
    [P in keyof T & keyof AggregateFaith]: P extends "_count" | "count"
        ? T[P] extends true
            ? number
            : Prisma.GetScalarType<T[P], AggregateFaith[P]>
        : Prisma.GetScalarType<T[P], AggregateFaith[P]>;
};

export type FaithGroupByArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.FaithWhereInput;
    orderBy?:
        | Prisma.FaithOrderByWithAggregationInput
        | Prisma.FaithOrderByWithAggregationInput[];
    by: Prisma.FaithScalarFieldEnum[] | Prisma.FaithScalarFieldEnum;
    having?: Prisma.FaithScalarWhereWithAggregatesInput;
    take?: number;
    skip?: number;
    _count?: FaithCountAggregateInputType | true;
    _min?: FaithMinAggregateInputType;
    _max?: FaithMaxAggregateInputType;
};

export type FaithGroupByOutputType = {
    id: string;
    church: string;
    userId: string;
    createdAt: Date;
    updatedAt: Date;
    _count: FaithCountAggregateOutputType | null;
    _min: FaithMinAggregateOutputType | null;
    _max: FaithMaxAggregateOutputType | null;
};

export type GetFaithGroupByPayload<T extends FaithGroupByArgs> =
    Prisma.PrismaPromise<
        Array<
            Prisma.PickEnumerable<FaithGroupByOutputType, T["by"]> & {
                [P in keyof T &
                    keyof FaithGroupByOutputType]: P extends "_count"
                    ? T[P] extends boolean
                        ? number
                        : Prisma.GetScalarType<T[P], FaithGroupByOutputType[P]>
                    : Prisma.GetScalarType<T[P], FaithGroupByOutputType[P]>;
            }
        >
    >;

export type FaithWhereInput = {
    AND?: Prisma.FaithWhereInput | Prisma.FaithWhereInput[];
    OR?: Prisma.FaithWhereInput[];
    NOT?: Prisma.FaithWhereInput | Prisma.FaithWhereInput[];
    id?: Prisma.StringFilter<"Faith"> | string;
    church?: Prisma.StringFilter<"Faith"> | string;
    userId?: Prisma.StringFilter<"Faith"> | string;
    createdAt?: Prisma.DateTimeFilter<"Faith"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"Faith"> | Date | string;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
    tithes?: Prisma.TitheListRelationFilter;
    offers?: Prisma.OfferListRelationFilter;
};

export type FaithOrderByWithRelationInput = {
    id?: Prisma.SortOrder;
    church?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    user?: Prisma.UserOrderByWithRelationInput;
    tithes?: Prisma.TitheOrderByRelationAggregateInput;
    offers?: Prisma.OfferOrderByRelationAggregateInput;
};

export type FaithWhereUniqueInput = Prisma.AtLeast<
    {
        id?: string;
        AND?: Prisma.FaithWhereInput | Prisma.FaithWhereInput[];
        OR?: Prisma.FaithWhereInput[];
        NOT?: Prisma.FaithWhereInput | Prisma.FaithWhereInput[];
        church?: Prisma.StringFilter<"Faith"> | string;
        userId?: Prisma.StringFilter<"Faith"> | string;
        createdAt?: Prisma.DateTimeFilter<"Faith"> | Date | string;
        updatedAt?: Prisma.DateTimeFilter<"Faith"> | Date | string;
        user?: Prisma.XOR<
            Prisma.UserScalarRelationFilter,
            Prisma.UserWhereInput
        >;
        tithes?: Prisma.TitheListRelationFilter;
        offers?: Prisma.OfferListRelationFilter;
    },
    "id"
>;

export type FaithOrderByWithAggregationInput = {
    id?: Prisma.SortOrder;
    church?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
    _count?: Prisma.FaithCountOrderByAggregateInput;
    _max?: Prisma.FaithMaxOrderByAggregateInput;
    _min?: Prisma.FaithMinOrderByAggregateInput;
};

export type FaithScalarWhereWithAggregatesInput = {
    AND?:
        | Prisma.FaithScalarWhereWithAggregatesInput
        | Prisma.FaithScalarWhereWithAggregatesInput[];
    OR?: Prisma.FaithScalarWhereWithAggregatesInput[];
    NOT?:
        | Prisma.FaithScalarWhereWithAggregatesInput
        | Prisma.FaithScalarWhereWithAggregatesInput[];
    id?: Prisma.StringWithAggregatesFilter<"Faith"> | string;
    church?: Prisma.StringWithAggregatesFilter<"Faith"> | string;
    userId?: Prisma.StringWithAggregatesFilter<"Faith"> | string;
    createdAt?: Prisma.DateTimeWithAggregatesFilter<"Faith"> | Date | string;
    updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Faith"> | Date | string;
};

export type FaithCreateInput = {
    id?: string;
    church: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    user: Prisma.UserCreateNestedOneWithoutFaithsInput;
    tithes?: Prisma.TitheCreateNestedManyWithoutFaithInput;
    offers?: Prisma.OfferCreateNestedManyWithoutFaithInput;
};

export type FaithUncheckedCreateInput = {
    id?: string;
    church: string;
    userId: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    tithes?: Prisma.TitheUncheckedCreateNestedManyWithoutFaithInput;
    offers?: Prisma.OfferUncheckedCreateNestedManyWithoutFaithInput;
};

export type FaithUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    user?: Prisma.UserUpdateOneRequiredWithoutFaithsNestedInput;
    tithes?: Prisma.TitheUpdateManyWithoutFaithNestedInput;
    offers?: Prisma.OfferUpdateManyWithoutFaithNestedInput;
};

export type FaithUncheckedUpdateInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    tithes?: Prisma.TitheUncheckedUpdateManyWithoutFaithNestedInput;
    offers?: Prisma.OfferUncheckedUpdateManyWithoutFaithNestedInput;
};

export type FaithCreateManyInput = {
    id?: string;
    church: string;
    userId: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type FaithUpdateManyMutationInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type FaithUncheckedUpdateManyInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type FaithListRelationFilter = {
    every?: Prisma.FaithWhereInput;
    some?: Prisma.FaithWhereInput;
    none?: Prisma.FaithWhereInput;
};

export type FaithOrderByRelationAggregateInput = {
    _count?: Prisma.SortOrder;
};

export type FaithCountOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    church?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type FaithMaxOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    church?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type FaithMinOrderByAggregateInput = {
    id?: Prisma.SortOrder;
    church?: Prisma.SortOrder;
    userId?: Prisma.SortOrder;
    createdAt?: Prisma.SortOrder;
    updatedAt?: Prisma.SortOrder;
};

export type FaithScalarRelationFilter = {
    is?: Prisma.FaithWhereInput;
    isNot?: Prisma.FaithWhereInput;
};

export type FaithCreateNestedManyWithoutUserInput = {
    create?:
        | Prisma.XOR<
              Prisma.FaithCreateWithoutUserInput,
              Prisma.FaithUncheckedCreateWithoutUserInput
          >
        | Prisma.FaithCreateWithoutUserInput[]
        | Prisma.FaithUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.FaithCreateOrConnectWithoutUserInput
        | Prisma.FaithCreateOrConnectWithoutUserInput[];
    createMany?: Prisma.FaithCreateManyUserInputEnvelope;
    connect?: Prisma.FaithWhereUniqueInput | Prisma.FaithWhereUniqueInput[];
};

export type FaithUncheckedCreateNestedManyWithoutUserInput = {
    create?:
        | Prisma.XOR<
              Prisma.FaithCreateWithoutUserInput,
              Prisma.FaithUncheckedCreateWithoutUserInput
          >
        | Prisma.FaithCreateWithoutUserInput[]
        | Prisma.FaithUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.FaithCreateOrConnectWithoutUserInput
        | Prisma.FaithCreateOrConnectWithoutUserInput[];
    createMany?: Prisma.FaithCreateManyUserInputEnvelope;
    connect?: Prisma.FaithWhereUniqueInput | Prisma.FaithWhereUniqueInput[];
};

export type FaithUpdateManyWithoutUserNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.FaithCreateWithoutUserInput,
              Prisma.FaithUncheckedCreateWithoutUserInput
          >
        | Prisma.FaithCreateWithoutUserInput[]
        | Prisma.FaithUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.FaithCreateOrConnectWithoutUserInput
        | Prisma.FaithCreateOrConnectWithoutUserInput[];
    upsert?:
        | Prisma.FaithUpsertWithWhereUniqueWithoutUserInput
        | Prisma.FaithUpsertWithWhereUniqueWithoutUserInput[];
    createMany?: Prisma.FaithCreateManyUserInputEnvelope;
    set?: Prisma.FaithWhereUniqueInput | Prisma.FaithWhereUniqueInput[];
    disconnect?: Prisma.FaithWhereUniqueInput | Prisma.FaithWhereUniqueInput[];
    delete?: Prisma.FaithWhereUniqueInput | Prisma.FaithWhereUniqueInput[];
    connect?: Prisma.FaithWhereUniqueInput | Prisma.FaithWhereUniqueInput[];
    update?:
        | Prisma.FaithUpdateWithWhereUniqueWithoutUserInput
        | Prisma.FaithUpdateWithWhereUniqueWithoutUserInput[];
    updateMany?:
        | Prisma.FaithUpdateManyWithWhereWithoutUserInput
        | Prisma.FaithUpdateManyWithWhereWithoutUserInput[];
    deleteMany?: Prisma.FaithScalarWhereInput | Prisma.FaithScalarWhereInput[];
};

export type FaithUncheckedUpdateManyWithoutUserNestedInput = {
    create?:
        | Prisma.XOR<
              Prisma.FaithCreateWithoutUserInput,
              Prisma.FaithUncheckedCreateWithoutUserInput
          >
        | Prisma.FaithCreateWithoutUserInput[]
        | Prisma.FaithUncheckedCreateWithoutUserInput[];
    connectOrCreate?:
        | Prisma.FaithCreateOrConnectWithoutUserInput
        | Prisma.FaithCreateOrConnectWithoutUserInput[];
    upsert?:
        | Prisma.FaithUpsertWithWhereUniqueWithoutUserInput
        | Prisma.FaithUpsertWithWhereUniqueWithoutUserInput[];
    createMany?: Prisma.FaithCreateManyUserInputEnvelope;
    set?: Prisma.FaithWhereUniqueInput | Prisma.FaithWhereUniqueInput[];
    disconnect?: Prisma.FaithWhereUniqueInput | Prisma.FaithWhereUniqueInput[];
    delete?: Prisma.FaithWhereUniqueInput | Prisma.FaithWhereUniqueInput[];
    connect?: Prisma.FaithWhereUniqueInput | Prisma.FaithWhereUniqueInput[];
    update?:
        | Prisma.FaithUpdateWithWhereUniqueWithoutUserInput
        | Prisma.FaithUpdateWithWhereUniqueWithoutUserInput[];
    updateMany?:
        | Prisma.FaithUpdateManyWithWhereWithoutUserInput
        | Prisma.FaithUpdateManyWithWhereWithoutUserInput[];
    deleteMany?: Prisma.FaithScalarWhereInput | Prisma.FaithScalarWhereInput[];
};

export type FaithCreateNestedOneWithoutTithesInput = {
    create?: Prisma.XOR<
        Prisma.FaithCreateWithoutTithesInput,
        Prisma.FaithUncheckedCreateWithoutTithesInput
    >;
    connectOrCreate?: Prisma.FaithCreateOrConnectWithoutTithesInput;
    connect?: Prisma.FaithWhereUniqueInput;
};

export type FaithUpdateOneRequiredWithoutTithesNestedInput = {
    create?: Prisma.XOR<
        Prisma.FaithCreateWithoutTithesInput,
        Prisma.FaithUncheckedCreateWithoutTithesInput
    >;
    connectOrCreate?: Prisma.FaithCreateOrConnectWithoutTithesInput;
    upsert?: Prisma.FaithUpsertWithoutTithesInput;
    connect?: Prisma.FaithWhereUniqueInput;
    update?: Prisma.XOR<
        Prisma.XOR<
            Prisma.FaithUpdateToOneWithWhereWithoutTithesInput,
            Prisma.FaithUpdateWithoutTithesInput
        >,
        Prisma.FaithUncheckedUpdateWithoutTithesInput
    >;
};

export type FaithCreateNestedOneWithoutOffersInput = {
    create?: Prisma.XOR<
        Prisma.FaithCreateWithoutOffersInput,
        Prisma.FaithUncheckedCreateWithoutOffersInput
    >;
    connectOrCreate?: Prisma.FaithCreateOrConnectWithoutOffersInput;
    connect?: Prisma.FaithWhereUniqueInput;
};

export type FaithUpdateOneRequiredWithoutOffersNestedInput = {
    create?: Prisma.XOR<
        Prisma.FaithCreateWithoutOffersInput,
        Prisma.FaithUncheckedCreateWithoutOffersInput
    >;
    connectOrCreate?: Prisma.FaithCreateOrConnectWithoutOffersInput;
    upsert?: Prisma.FaithUpsertWithoutOffersInput;
    connect?: Prisma.FaithWhereUniqueInput;
    update?: Prisma.XOR<
        Prisma.XOR<
            Prisma.FaithUpdateToOneWithWhereWithoutOffersInput,
            Prisma.FaithUpdateWithoutOffersInput
        >,
        Prisma.FaithUncheckedUpdateWithoutOffersInput
    >;
};

export type FaithCreateWithoutUserInput = {
    id?: string;
    church: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    tithes?: Prisma.TitheCreateNestedManyWithoutFaithInput;
    offers?: Prisma.OfferCreateNestedManyWithoutFaithInput;
};

export type FaithUncheckedCreateWithoutUserInput = {
    id?: string;
    church: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    tithes?: Prisma.TitheUncheckedCreateNestedManyWithoutFaithInput;
    offers?: Prisma.OfferUncheckedCreateNestedManyWithoutFaithInput;
};

export type FaithCreateOrConnectWithoutUserInput = {
    where: Prisma.FaithWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.FaithCreateWithoutUserInput,
        Prisma.FaithUncheckedCreateWithoutUserInput
    >;
};

export type FaithCreateManyUserInputEnvelope = {
    data: Prisma.FaithCreateManyUserInput | Prisma.FaithCreateManyUserInput[];
    skipDuplicates?: boolean;
};

export type FaithUpsertWithWhereUniqueWithoutUserInput = {
    where: Prisma.FaithWhereUniqueInput;
    update: Prisma.XOR<
        Prisma.FaithUpdateWithoutUserInput,
        Prisma.FaithUncheckedUpdateWithoutUserInput
    >;
    create: Prisma.XOR<
        Prisma.FaithCreateWithoutUserInput,
        Prisma.FaithUncheckedCreateWithoutUserInput
    >;
};

export type FaithUpdateWithWhereUniqueWithoutUserInput = {
    where: Prisma.FaithWhereUniqueInput;
    data: Prisma.XOR<
        Prisma.FaithUpdateWithoutUserInput,
        Prisma.FaithUncheckedUpdateWithoutUserInput
    >;
};

export type FaithUpdateManyWithWhereWithoutUserInput = {
    where: Prisma.FaithScalarWhereInput;
    data: Prisma.XOR<
        Prisma.FaithUpdateManyMutationInput,
        Prisma.FaithUncheckedUpdateManyWithoutUserInput
    >;
};

export type FaithScalarWhereInput = {
    AND?: Prisma.FaithScalarWhereInput | Prisma.FaithScalarWhereInput[];
    OR?: Prisma.FaithScalarWhereInput[];
    NOT?: Prisma.FaithScalarWhereInput | Prisma.FaithScalarWhereInput[];
    id?: Prisma.StringFilter<"Faith"> | string;
    church?: Prisma.StringFilter<"Faith"> | string;
    userId?: Prisma.StringFilter<"Faith"> | string;
    createdAt?: Prisma.DateTimeFilter<"Faith"> | Date | string;
    updatedAt?: Prisma.DateTimeFilter<"Faith"> | Date | string;
};

export type FaithCreateWithoutTithesInput = {
    id?: string;
    church: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    user: Prisma.UserCreateNestedOneWithoutFaithsInput;
    offers?: Prisma.OfferCreateNestedManyWithoutFaithInput;
};

export type FaithUncheckedCreateWithoutTithesInput = {
    id?: string;
    church: string;
    userId: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    offers?: Prisma.OfferUncheckedCreateNestedManyWithoutFaithInput;
};

export type FaithCreateOrConnectWithoutTithesInput = {
    where: Prisma.FaithWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.FaithCreateWithoutTithesInput,
        Prisma.FaithUncheckedCreateWithoutTithesInput
    >;
};

export type FaithUpsertWithoutTithesInput = {
    update: Prisma.XOR<
        Prisma.FaithUpdateWithoutTithesInput,
        Prisma.FaithUncheckedUpdateWithoutTithesInput
    >;
    create: Prisma.XOR<
        Prisma.FaithCreateWithoutTithesInput,
        Prisma.FaithUncheckedCreateWithoutTithesInput
    >;
    where?: Prisma.FaithWhereInput;
};

export type FaithUpdateToOneWithWhereWithoutTithesInput = {
    where?: Prisma.FaithWhereInput;
    data: Prisma.XOR<
        Prisma.FaithUpdateWithoutTithesInput,
        Prisma.FaithUncheckedUpdateWithoutTithesInput
    >;
};

export type FaithUpdateWithoutTithesInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    user?: Prisma.UserUpdateOneRequiredWithoutFaithsNestedInput;
    offers?: Prisma.OfferUpdateManyWithoutFaithNestedInput;
};

export type FaithUncheckedUpdateWithoutTithesInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    offers?: Prisma.OfferUncheckedUpdateManyWithoutFaithNestedInput;
};

export type FaithCreateWithoutOffersInput = {
    id?: string;
    church: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    user: Prisma.UserCreateNestedOneWithoutFaithsInput;
    tithes?: Prisma.TitheCreateNestedManyWithoutFaithInput;
};

export type FaithUncheckedCreateWithoutOffersInput = {
    id?: string;
    church: string;
    userId: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
    tithes?: Prisma.TitheUncheckedCreateNestedManyWithoutFaithInput;
};

export type FaithCreateOrConnectWithoutOffersInput = {
    where: Prisma.FaithWhereUniqueInput;
    create: Prisma.XOR<
        Prisma.FaithCreateWithoutOffersInput,
        Prisma.FaithUncheckedCreateWithoutOffersInput
    >;
};

export type FaithUpsertWithoutOffersInput = {
    update: Prisma.XOR<
        Prisma.FaithUpdateWithoutOffersInput,
        Prisma.FaithUncheckedUpdateWithoutOffersInput
    >;
    create: Prisma.XOR<
        Prisma.FaithCreateWithoutOffersInput,
        Prisma.FaithUncheckedCreateWithoutOffersInput
    >;
    where?: Prisma.FaithWhereInput;
};

export type FaithUpdateToOneWithWhereWithoutOffersInput = {
    where?: Prisma.FaithWhereInput;
    data: Prisma.XOR<
        Prisma.FaithUpdateWithoutOffersInput,
        Prisma.FaithUncheckedUpdateWithoutOffersInput
    >;
};

export type FaithUpdateWithoutOffersInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    user?: Prisma.UserUpdateOneRequiredWithoutFaithsNestedInput;
    tithes?: Prisma.TitheUpdateManyWithoutFaithNestedInput;
};

export type FaithUncheckedUpdateWithoutOffersInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    userId?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    tithes?: Prisma.TitheUncheckedUpdateManyWithoutFaithNestedInput;
};

export type FaithCreateManyUserInput = {
    id?: string;
    church: string;
    createdAt?: Date | string;
    updatedAt?: Date | string;
};

export type FaithUpdateWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    tithes?: Prisma.TitheUpdateManyWithoutFaithNestedInput;
    offers?: Prisma.OfferUpdateManyWithoutFaithNestedInput;
};

export type FaithUncheckedUpdateWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    tithes?: Prisma.TitheUncheckedUpdateManyWithoutFaithNestedInput;
    offers?: Prisma.OfferUncheckedUpdateManyWithoutFaithNestedInput;
};

export type FaithUncheckedUpdateManyWithoutUserInput = {
    id?: Prisma.StringFieldUpdateOperationsInput | string;
    church?: Prisma.StringFieldUpdateOperationsInput | string;
    createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
    updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

/**
 * Count Type FaithCountOutputType
 */

export type FaithCountOutputType = {
    tithes: number;
    offers: number;
};

export type FaithCountOutputTypeSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    tithes?: boolean | FaithCountOutputTypeCountTithesArgs;
    offers?: boolean | FaithCountOutputTypeCountOffersArgs;
};

/**
 * FaithCountOutputType without action
 */
export type FaithCountOutputTypeDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the FaithCountOutputType
     */
    select?: Prisma.FaithCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * FaithCountOutputType without action
 */
export type FaithCountOutputTypeCountTithesArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.TitheWhereInput;
};

/**
 * FaithCountOutputType without action
 */
export type FaithCountOutputTypeCountOffersArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    where?: Prisma.OfferWhereInput;
};

export type FaithSelect<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        church?: boolean;
        userId?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
        tithes?: boolean | Prisma.Faith$tithesArgs<ExtArgs>;
        offers?: boolean | Prisma.Faith$offersArgs<ExtArgs>;
        _count?: boolean | Prisma.FaithCountOutputTypeDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["faith"]
>;

export type FaithSelectCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        church?: boolean;
        userId?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["faith"]
>;

export type FaithSelectUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
    {
        id?: boolean;
        church?: boolean;
        userId?: boolean;
        createdAt?: boolean;
        updatedAt?: boolean;
        user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    },
    ExtArgs["result"]["faith"]
>;

export type FaithSelectScalar = {
    id?: boolean;
    church?: boolean;
    userId?: boolean;
    createdAt?: boolean;
    updatedAt?: boolean;
};

export type FaithOmit<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
    "id" | "church" | "userId" | "createdAt" | "updatedAt",
    ExtArgs["result"]["faith"]
>;
export type FaithInclude<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    tithes?: boolean | Prisma.Faith$tithesArgs<ExtArgs>;
    offers?: boolean | Prisma.Faith$offersArgs<ExtArgs>;
    _count?: boolean | Prisma.FaithCountOutputTypeDefaultArgs<ExtArgs>;
};
export type FaithIncludeCreateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type FaithIncludeUpdateManyAndReturn<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};

export type $FaithPayload<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    name: "Faith";
    objects: {
        user: Prisma.$UserPayload<ExtArgs>;
        tithes: Prisma.$TithePayload<ExtArgs>[];
        offers: Prisma.$OfferPayload<ExtArgs>[];
    };
    scalars: runtime.Types.Extensions.GetPayloadResult<
        {
            id: string;
            church: string;
            userId: string;
            createdAt: Date;
            updatedAt: Date;
        },
        ExtArgs["result"]["faith"]
    >;
    composites: {};
};

export type FaithGetPayload<
    S extends boolean | null | undefined | FaithDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$FaithPayload, S>;

export type FaithCountArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = Omit<FaithFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
    select?: FaithCountAggregateInputType | true;
};

export interface FaithDelegate<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> {
    [K: symbol]: {
        types: Prisma.TypeMap<ExtArgs>["model"]["Faith"];
        meta: { name: "Faith" };
    };
    /**
     * Find zero or one Faith that matches the filter.
     * @param {FaithFindUniqueArgs} args - Arguments to find a Faith
     * @example
     * // Get one Faith
     * const faith = await prisma.faith.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends FaithFindUniqueArgs>(
        args: Prisma.SelectSubset<T, FaithFindUniqueArgs<ExtArgs>>,
    ): Prisma.Prisma__FaithClient<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "findUnique",
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find one Faith that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {FaithFindUniqueOrThrowArgs} args - Arguments to find a Faith
     * @example
     * // Get one Faith
     * const faith = await prisma.faith.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends FaithFindUniqueOrThrowArgs>(
        args: Prisma.SelectSubset<T, FaithFindUniqueOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__FaithClient<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "findUniqueOrThrow",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first Faith that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {FaithFindFirstArgs} args - Arguments to find a Faith
     * @example
     * // Get one Faith
     * const faith = await prisma.faith.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends FaithFindFirstArgs>(
        args?: Prisma.SelectSubset<T, FaithFindFirstArgs<ExtArgs>>,
    ): Prisma.Prisma__FaithClient<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "findFirst",
            GlobalOmitOptions
        > | null,
        null,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find the first Faith that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {FaithFindFirstOrThrowArgs} args - Arguments to find a Faith
     * @example
     * // Get one Faith
     * const faith = await prisma.faith.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends FaithFindFirstOrThrowArgs>(
        args?: Prisma.SelectSubset<T, FaithFindFirstOrThrowArgs<ExtArgs>>,
    ): Prisma.Prisma__FaithClient<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "findFirstOrThrow",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Find zero or more Faiths that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {FaithFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all Faiths
     * const faiths = await prisma.faith.findMany()
     *
     * // Get first 10 Faiths
     * const faiths = await prisma.faith.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const faithWithIdOnly = await prisma.faith.findMany({ select: { id: true } })
     *
     */
    findMany<T extends FaithFindManyArgs>(
        args?: Prisma.SelectSubset<T, FaithFindManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "findMany",
            GlobalOmitOptions
        >
    >;

    /**
     * Create a Faith.
     * @param {FaithCreateArgs} args - Arguments to create a Faith.
     * @example
     * // Create one Faith
     * const Faith = await prisma.faith.create({
     *   data: {
     *     // ... data to create a Faith
     *   }
     * })
     *
     */
    create<T extends FaithCreateArgs>(
        args: Prisma.SelectSubset<T, FaithCreateArgs<ExtArgs>>,
    ): Prisma.Prisma__FaithClient<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "create",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Create many Faiths.
     * @param {FaithCreateManyArgs} args - Arguments to create many Faiths.
     * @example
     * // Create many Faiths
     * const faith = await prisma.faith.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     */
    createMany<T extends FaithCreateManyArgs>(
        args?: Prisma.SelectSubset<T, FaithCreateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Create many Faiths and returns the data saved in the database.
     * @param {FaithCreateManyAndReturnArgs} args - Arguments to create many Faiths.
     * @example
     * // Create many Faiths
     * const faith = await prisma.faith.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many Faiths and only return the `id`
     * const faithWithIdOnly = await prisma.faith.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    createManyAndReturn<T extends FaithCreateManyAndReturnArgs>(
        args?: Prisma.SelectSubset<T, FaithCreateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "createManyAndReturn",
            GlobalOmitOptions
        >
    >;

    /**
     * Delete a Faith.
     * @param {FaithDeleteArgs} args - Arguments to delete one Faith.
     * @example
     * // Delete one Faith
     * const Faith = await prisma.faith.delete({
     *   where: {
     *     // ... filter to delete one Faith
     *   }
     * })
     *
     */
    delete<T extends FaithDeleteArgs>(
        args: Prisma.SelectSubset<T, FaithDeleteArgs<ExtArgs>>,
    ): Prisma.Prisma__FaithClient<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "delete",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Update one Faith.
     * @param {FaithUpdateArgs} args - Arguments to update one Faith.
     * @example
     * // Update one Faith
     * const faith = await prisma.faith.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    update<T extends FaithUpdateArgs>(
        args: Prisma.SelectSubset<T, FaithUpdateArgs<ExtArgs>>,
    ): Prisma.Prisma__FaithClient<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "update",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Delete zero or more Faiths.
     * @param {FaithDeleteManyArgs} args - Arguments to filter Faiths to delete.
     * @example
     * // Delete a few Faiths
     * const { count } = await prisma.faith.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     *
     */
    deleteMany<T extends FaithDeleteManyArgs>(
        args?: Prisma.SelectSubset<T, FaithDeleteManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more Faiths.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {FaithUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many Faiths
     * const faith = await prisma.faith.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     *
     */
    updateMany<T extends FaithUpdateManyArgs>(
        args: Prisma.SelectSubset<T, FaithUpdateManyArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<Prisma.BatchPayload>;

    /**
     * Update zero or more Faiths and returns the data updated in the database.
     * @param {FaithUpdateManyAndReturnArgs} args - Arguments to update many Faiths.
     * @example
     * // Update many Faiths
     * const faith = await prisma.faith.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more Faiths and only return the `id`
     * const faithWithIdOnly = await prisma.faith.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     *
     */
    updateManyAndReturn<T extends FaithUpdateManyAndReturnArgs>(
        args: Prisma.SelectSubset<T, FaithUpdateManyAndReturnArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "updateManyAndReturn",
            GlobalOmitOptions
        >
    >;

    /**
     * Create or update one Faith.
     * @param {FaithUpsertArgs} args - Arguments to update or create a Faith.
     * @example
     * // Update or create a Faith
     * const faith = await prisma.faith.upsert({
     *   create: {
     *     // ... data to create a Faith
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the Faith we want to update
     *   }
     * })
     */
    upsert<T extends FaithUpsertArgs>(
        args: Prisma.SelectSubset<T, FaithUpsertArgs<ExtArgs>>,
    ): Prisma.Prisma__FaithClient<
        runtime.Types.Result.GetResult<
            Prisma.$FaithPayload<ExtArgs>,
            T,
            "upsert",
            GlobalOmitOptions
        >,
        never,
        ExtArgs,
        GlobalOmitOptions
    >;

    /**
     * Count the number of Faiths.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {FaithCountArgs} args - Arguments to filter Faiths to count.
     * @example
     * // Count the number of Faiths
     * const count = await prisma.faith.count({
     *   where: {
     *     // ... the filter for the Faiths we want to count
     *   }
     * })
     **/
    count<T extends FaithCountArgs>(
        args?: Prisma.Subset<T, FaithCountArgs>,
    ): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<"select", any>
            ? T["select"] extends true
                ? number
                : Prisma.GetScalarType<
                      T["select"],
                      FaithCountAggregateOutputType
                  >
            : number
    >;

    /**
     * Allows you to perform aggregations operations on a Faith.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {FaithAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     **/
    aggregate<T extends FaithAggregateArgs>(
        args: Prisma.Subset<T, FaithAggregateArgs>,
    ): Prisma.PrismaPromise<GetFaithAggregateType<T>>;

    /**
     * Group by Faith.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {FaithGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     *
     **/
    groupBy<
        T extends FaithGroupByArgs,
        HasSelectOrTake extends Prisma.Or<
            Prisma.Extends<"skip", Prisma.Keys<T>>,
            Prisma.Extends<"take", Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
            ? { orderBy: FaithGroupByArgs["orderBy"] }
            : { orderBy?: FaithGroupByArgs["orderBy"] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<
            Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
        >,
        ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T["having"]>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
            ? `Error: "by" must not be empty.`
            : HavingValid extends Prisma.False
              ? {
                    [P in HavingFields]: P extends ByFields
                        ? never
                        : P extends string
                          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                          : [
                                Error,
                                "Field ",
                                P,
                                ` in "having" needs to be provided in "by"`,
                            ];
                }[HavingFields]
              : "take" extends Prisma.Keys<T>
                ? "orderBy" extends Prisma.Keys<T>
                    ? ByValid extends Prisma.True
                        ? {}
                        : {
                              [P in OrderFields]: P extends ByFields
                                  ? never
                                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                          }[OrderFields]
                    : 'Error: If you provide "take", you also need to provide "orderBy"'
                : "skip" extends Prisma.Keys<T>
                  ? "orderBy" extends Prisma.Keys<T>
                      ? ByValid extends Prisma.True
                          ? {}
                          : {
                                [P in OrderFields]: P extends ByFields
                                    ? never
                                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                            }[OrderFields]
                      : 'Error: If you provide "skip", you also need to provide "orderBy"'
                  : ByValid extends Prisma.True
                    ? {}
                    : {
                          [P in OrderFields]: P extends ByFields
                              ? never
                              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                      }[OrderFields],
    >(
        args: Prisma.SubsetIntersection<T, FaithGroupByArgs, OrderByArg> &
            InputErrors,
    ): {} extends InputErrors
        ? GetFaithGroupByPayload<T>
        : Prisma.PrismaPromise<InputErrors>;
    /**
     * Fields of the Faith model
     */
    readonly fields: FaithFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Faith.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FaithClient<
    T,
    Null = never,
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
    GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise";
    user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>,
    ): Prisma.Prisma__UserClient<
        | runtime.Types.Result.GetResult<
              Prisma.$UserPayload<ExtArgs>,
              T,
              "findUniqueOrThrow",
              GlobalOmitOptions
          >
        | Null,
        Null,
        ExtArgs,
        GlobalOmitOptions
    >;
    tithes<T extends Prisma.Faith$tithesArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.Faith$tithesArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        | runtime.Types.Result.GetResult<
              Prisma.$TithePayload<ExtArgs>,
              T,
              "findMany",
              GlobalOmitOptions
          >
        | Null
    >;
    offers<T extends Prisma.Faith$offersArgs<ExtArgs> = {}>(
        args?: Prisma.Subset<T, Prisma.Faith$offersArgs<ExtArgs>>,
    ): Prisma.PrismaPromise<
        | runtime.Types.Result.GetResult<
              Prisma.$OfferPayload<ExtArgs>,
              T,
              "findMany",
              GlobalOmitOptions
          >
        | Null
    >;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(
        onfulfilled?:
            | ((value: T) => TResult1 | PromiseLike<TResult1>)
            | undefined
            | null,
        onrejected?:
            | ((reason: any) => TResult2 | PromiseLike<TResult2>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(
        onrejected?:
            | ((reason: any) => TResult | PromiseLike<TResult>)
            | undefined
            | null,
    ): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(
        onfinally?: (() => void) | undefined | null,
    ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the Faith model
 */
export interface FaithFieldRefs {
    readonly id: Prisma.FieldRef<"Faith", "String">;
    readonly church: Prisma.FieldRef<"Faith", "String">;
    readonly userId: Prisma.FieldRef<"Faith", "String">;
    readonly createdAt: Prisma.FieldRef<"Faith", "DateTime">;
    readonly updatedAt: Prisma.FieldRef<"Faith", "DateTime">;
}

// Custom InputTypes
/**
 * Faith findUnique
 */
export type FaithFindUniqueArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithInclude<ExtArgs> | null;
    /**
     * Filter, which Faith to fetch.
     */
    where: Prisma.FaithWhereUniqueInput;
};

/**
 * Faith findUniqueOrThrow
 */
export type FaithFindUniqueOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithInclude<ExtArgs> | null;
    /**
     * Filter, which Faith to fetch.
     */
    where: Prisma.FaithWhereUniqueInput;
};

/**
 * Faith findFirst
 */
export type FaithFindFirstArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithInclude<ExtArgs> | null;
    /**
     * Filter, which Faith to fetch.
     */
    where?: Prisma.FaithWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Faiths to fetch.
     */
    orderBy?:
        | Prisma.FaithOrderByWithRelationInput
        | Prisma.FaithOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for Faiths.
     */
    cursor?: Prisma.FaithWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Faiths from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Faiths.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of Faiths.
     */
    distinct?: Prisma.FaithScalarFieldEnum | Prisma.FaithScalarFieldEnum[];
};

/**
 * Faith findFirstOrThrow
 */
export type FaithFindFirstOrThrowArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithInclude<ExtArgs> | null;
    /**
     * Filter, which Faith to fetch.
     */
    where?: Prisma.FaithWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Faiths to fetch.
     */
    orderBy?:
        | Prisma.FaithOrderByWithRelationInput
        | Prisma.FaithOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for searching for Faiths.
     */
    cursor?: Prisma.FaithWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Faiths from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Faiths.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of Faiths.
     */
    distinct?: Prisma.FaithScalarFieldEnum | Prisma.FaithScalarFieldEnum[];
};

/**
 * Faith findMany
 */
export type FaithFindManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithInclude<ExtArgs> | null;
    /**
     * Filter, which Faiths to fetch.
     */
    where?: Prisma.FaithWhereInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
     *
     * Determine the order of Faiths to fetch.
     */
    orderBy?:
        | Prisma.FaithOrderByWithRelationInput
        | Prisma.FaithOrderByWithRelationInput[];
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
     *
     * Sets the position for listing Faiths.
     */
    cursor?: Prisma.FaithWhereUniqueInput;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Take `±n` Faiths from the position of the cursor.
     */
    take?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
     *
     * Skip the first `n` Faiths.
     */
    skip?: number;
    /**
     * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
     *
     * Filter by unique combinations of Faiths.
     */
    distinct?: Prisma.FaithScalarFieldEnum | Prisma.FaithScalarFieldEnum[];
};

/**
 * Faith create
 */
export type FaithCreateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithInclude<ExtArgs> | null;
    /**
     * The data needed to create a Faith.
     */
    data: Prisma.XOR<Prisma.FaithCreateInput, Prisma.FaithUncheckedCreateInput>;
};

/**
 * Faith createMany
 */
export type FaithCreateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to create many Faiths.
     */
    data: Prisma.FaithCreateManyInput | Prisma.FaithCreateManyInput[];
    skipDuplicates?: boolean;
};

/**
 * Faith createManyAndReturn
 */
export type FaithCreateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelectCreateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * The data used to create many Faiths.
     */
    data: Prisma.FaithCreateManyInput | Prisma.FaithCreateManyInput[];
    skipDuplicates?: boolean;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * Faith update
 */
export type FaithUpdateArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithInclude<ExtArgs> | null;
    /**
     * The data needed to update a Faith.
     */
    data: Prisma.XOR<Prisma.FaithUpdateInput, Prisma.FaithUncheckedUpdateInput>;
    /**
     * Choose, which Faith to update.
     */
    where: Prisma.FaithWhereUniqueInput;
};

/**
 * Faith updateMany
 */
export type FaithUpdateManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * The data used to update Faiths.
     */
    data: Prisma.XOR<
        Prisma.FaithUpdateManyMutationInput,
        Prisma.FaithUncheckedUpdateManyInput
    >;
    /**
     * Filter which Faiths to update
     */
    where?: Prisma.FaithWhereInput;
    /**
     * Limit how many Faiths to update.
     */
    limit?: number;
};

/**
 * Faith updateManyAndReturn
 */
export type FaithUpdateManyAndReturnArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelectUpdateManyAndReturn<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * The data used to update Faiths.
     */
    data: Prisma.XOR<
        Prisma.FaithUpdateManyMutationInput,
        Prisma.FaithUncheckedUpdateManyInput
    >;
    /**
     * Filter which Faiths to update
     */
    where?: Prisma.FaithWhereInput;
    /**
     * Limit how many Faiths to update.
     */
    limit?: number;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * Faith upsert
 */
export type FaithUpsertArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithInclude<ExtArgs> | null;
    /**
     * The filter to search for the Faith to update in case it exists.
     */
    where: Prisma.FaithWhereUniqueInput;
    /**
     * In case the Faith found by the `where` argument doesn't exist, create a new Faith with this data.
     */
    create: Prisma.XOR<
        Prisma.FaithCreateInput,
        Prisma.FaithUncheckedCreateInput
    >;
    /**
     * In case the Faith was found with the provided `where` argument, update it with this data.
     */
    update: Prisma.XOR<
        Prisma.FaithUpdateInput,
        Prisma.FaithUncheckedUpdateInput
    >;
};

/**
 * Faith delete
 */
export type FaithDeleteArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithInclude<ExtArgs> | null;
    /**
     * Filter which Faith to delete.
     */
    where: Prisma.FaithWhereUniqueInput;
};

/**
 * Faith deleteMany
 */
export type FaithDeleteManyArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Filter which Faiths to delete
     */
    where?: Prisma.FaithWhereInput;
    /**
     * Limit how many Faiths to delete.
     */
    limit?: number;
};

/**
 * Faith.tithes
 */
export type Faith$tithesArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Tithe
     */
    select?: Prisma.TitheSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Tithe
     */
    omit?: Prisma.TitheOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.TitheInclude<ExtArgs> | null;
    where?: Prisma.TitheWhereInput;
    orderBy?:
        | Prisma.TitheOrderByWithRelationInput
        | Prisma.TitheOrderByWithRelationInput[];
    cursor?: Prisma.TitheWhereUniqueInput;
    take?: number;
    skip?: number;
    distinct?: Prisma.TitheScalarFieldEnum | Prisma.TitheScalarFieldEnum[];
};

/**
 * Faith.offers
 */
export type Faith$offersArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Offer
     */
    select?: Prisma.OfferSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Offer
     */
    omit?: Prisma.OfferOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.OfferInclude<ExtArgs> | null;
    where?: Prisma.OfferWhereInput;
    orderBy?:
        | Prisma.OfferOrderByWithRelationInput
        | Prisma.OfferOrderByWithRelationInput[];
    cursor?: Prisma.OfferWhereUniqueInput;
    take?: number;
    skip?: number;
    distinct?: Prisma.OfferScalarFieldEnum | Prisma.OfferScalarFieldEnum[];
};

/**
 * Faith without action
 */
export type FaithDefaultArgs<
    ExtArgs extends runtime.Types.Extensions.InternalArgs =
        runtime.Types.Extensions.DefaultArgs,
> = {
    /**
     * Select specific fields to fetch from the Faith
     */
    select?: Prisma.FaithSelect<ExtArgs> | null;
    /**
     * Omit specific fields from the Faith
     */
    omit?: Prisma.FaithOmit<ExtArgs> | null;
    /**
     * Choose, which related nodes to fetch as well
     */
    include?: Prisma.FaithInclude<ExtArgs> | null;
};
